import type { Topic } from "../schema";

export const topics: Topic[] = [
  {
    slug: "block-file-object",
    track: "hld",
    category: "Files",
    title: "Block vs file vs object storage",
    summary:
      "Three ways to persist bytes: disks you mount, filesystems you share, and HTTP objects you address by key. They are not interchangeable.",
    depth: "core",
    whyItMatters:
      "Dropbox, video, and databases all 'store files' but want different primitives. Putting a database on object storage without a designed FS, or putting a billion photos on NFS, are classic HLD mistakes.",
    theory: [
      "Block storage (EBS, persistent disks) is a virtual hard drive attached to one VM (sometimes multi-attach with caveats). The OS filesystems and databases expect this: POSIX-ish local disk, low latency, snapshots. It is not a user-facing photo API. Capacity and IOPS are the knobs. Multi-AZ block is usually 'replicate the disk' not 'many writers.'",
      "File storage (NFS, EFS, Filestore) is a shared hierarchical filesystem: many clients, paths, locks, POSIX semantics (to a point). Good for lift-and-shift, home directories, and some ML training data. Painful at huge small-file counts, and locking across regions is a trap. Latency is higher than local block.",
      "Object storage is a web API of blobs. No POSIX, cheap, durable, parallel. User media and lakes live here. You add a metadata DB for query. Hybrid designs: DB on block, shared scratch on file, media on object. 'The Dropbox problem' is syncing a filesystem illusion on top of objects plus a metadata store.",
    ],
    howItWorks: [
      "Databases and logs → block (local SSD/EBS) in the region's AZs.",
      "Shared POSIX apps or home dirs → file store, with eyes open on scale.",
      "User-generated bytes and artifacts → object + metadata DB + CDN.",
      "Do not mount S3 as FUSE for a latency-sensitive DB.",
      "Snapshot block volumes as part of backup; lifecycle objects separately.",
    ],
    whenToUse: [
      "Block: stateful data stores, boot volumes.",
      "File: collaborative POSIX, some analytics scratch.",
      "Object: media, backups, lake, anything CDN-fronted.",
    ],
    whenNotToUse: [
      "Do not put the only copy of Postgres on a network filesystem you do not understand.",
      "Do not implement Dropbox as 'everyone mounts NFS.'",
    ],
    tradeoffs: [
      "Block: fast and familiar, attached to a node, pricier at lake scale.",
      "File: shared semantics, ops and scale limits.",
      "Object: scale and cost, high latency and no real POSIX.",
    ],
    interviewTips: [
      "For Dropbox/YouTube, say object for bytes, SQL for metadata, block only under the databases.",
      "If they say 'filesystem,' ask how many files and whether they need POSIX.",
    ],
    pitfalls: [
      "Single-AZ block volume for a 'HA' database.",
      "Millions of tiny files on NFS.",
      "Treating object listing as a directory walk in the request path.",
    ],
    practiceIdeas: [
      "Assign block/file/object to every box in a Dropbox design.",
      "Explain why a video transcoder uses local block scratch then writes objects.",
    ],
    related: [
      "object-storage",
      "dropbox",
      "cdn-origin",
      "chunked-resumable-upload",
      "youtube",
      "encryption",
    ],
  },
  {
    slug: "cdn-origin",
    track: "hld",
    category: "Files",
    title: "CDN and origin design",
    summary:
      "How the edge talks to object storage or an origin fleet: cache keys, shields, signed URLs, and range requests for media.",
    depth: "next",
    whyItMatters:
      "A CDN without an origin plan still melts S3 or your app. File/video designs live or die on cache hit ratio, range requests, and whether the origin is the bucket or a compute layer (image resize, auth).",
    theory: [
      "Origin is whoever the PoP fetches from on miss: typically a bucket or an origin server. An origin shield (regional mid-tier) collapses concurrent misses. Cache key should ignore junk query params. Range requests (bytes=) let video players seek; the CDN should cache ranges or the whole object intelligently. Immutable keys (hash in the path) beat purge.",
      "Private content: the user hits your API for a short-lived signed URL or signed cookie; the CDN validates and fetches from a private bucket. Do not stream every private byte through the API. For transformations (resize, watermark), either precompute and store variants or use an on-the-fly origin that caches results at the edge (with CPU/DoS care).",
      "Origin load is miss_rate × QPS × size. A 1% miss on 100k QPS of 1 MB images is 1k origin GETs and 8 Gbit/s. That number decides shield, prefetch, and whether you need more than one origin region.",
    ],
    howItWorks: [
      "Put CloudFront/Fastly/etc. in front of a private bucket.",
      "Version objects; long TTL; purge by key only when you must.",
      "Sign URLs for private media; keep listing disabled.",
      "Enable shield / request collapsing; support HTTP range.",
      "Precompute common image sizes; lazy-compute the long tail.",
    ],
    whenToUse: [
      "Any public or private media at consumer scale.",
      "Software downloads and large static sites.",
      "Video on demand (HLS/DASH segments are CDN-native).",
    ],
    whenNotToUse: [
      "Tiny, unique, authenticated JSON at low QPS — extra hop may not pay.",
      "Origin that runs a heavy uncached transform per request without limits.",
    ],
    tradeoffs: [
      "Bucket as origin: simple, limited logic.",
      "Compute origin: transforms and auth, easier to stampede.",
      "Many variants on disk: hit rate and storage vs on-the-fly CPU.",
    ],
    interviewTips: [
      "Do the miss-bandwidth math once — it justifies the CDN more than adjectives.",
      "For Instagram, mention a few resized variants stored, not infinite on-the-fly.",
    ],
    pitfalls: [
      "Cache key includes a unique token so hit rate is 0.",
      "Signing URLs that live for a week in a screenshot.",
      "No range support — mobile video restarts on seek.",
    ],
    practiceIdeas: [
      "Design signed URL + CDN + S3 for a private Dropbox download.",
      "Estimate origin QPS for a World Cup highlight at 5% miss.",
    ],
    related: [
      "cdn",
      "object-storage",
      "image-video-pipelines",
      "instagram",
      "youtube",
      "dropbox",
    ],
  },
  {
    slug: "chunked-resumable-upload",
    track: "hld",
    category: "Files",
    title: "Chunked and resumable uploads",
    summary:
      "Split large files into parts, upload in parallel, retry a part not the whole file, then assemble — the only sane path for GB uploads on phones.",
    depth: "next",
    whyItMatters:
      "Dropbox, YouTube, and Drive interviews all hit 'what if the user goes through a tunnel.' Resumable multipart is the answer: session, part ETags, checksums, and complete as an atomic-ish step.",
    theory: [
      "Protocol shape: client starts a session (file id, size, optional hash), gets a session token, PUTs parts (5–16 MB typical) with part numbers, then completes. S3 multipart is the industry template. TUS and similar standards exist for app-level resume. Parallel parts saturate the NIC; too small parts explode request costs and complete time.",
      "Resume: the client asks which parts the server already has (ETags) and sends the rest. Idempotent part PUT is required. Complete verifies part list and optional whole-file checksum; then you write metadata and enqueue processing. Abandoned sessions need a lifecycle abort so incomplete parts do not bill forever.",
      "Do not proxy parts through a single API box if you can presign each part to object storage. The API owns auth, session, and complete. Virus scan and transcode happen after complete, asynchronously. Dedup: if the content hash already exists, skip bytes (Dropbox magic).",
    ],
    howItWorks: [
      "POST /uploads → upload_id; client PUTs parts to presigned URLs.",
      "Store part ETags; GET status for resume.",
      "POST complete → verify → object exists → metadata row → 202 processing.",
      "Abort incomplete after N days; metric abandoned bytes.",
      "Checksum per part and optional Merkle/whole-file hash.",
    ],
    whenToUse: [
      "Any file larger than a few MB on unreliable networks.",
      "Video, backups, raw photos, dataset uploads.",
      "When you want parallel part upload for throughput.",
    ],
    whenNotToUse: [
      "Avatar 100 KB — a single PUT is simpler.",
      "Streaming live video — that is a different ingest (chunked live, not multipart assemble).",
    ],
    tradeoffs: [
      "Smaller parts: better resume granularity, more requests and complete overhead.",
      "Presigned direct-to-S3: cheap API, harder to scan mid-upload.",
      "Content-hash dedup: save storage, privacy/timing side channels if naive.",
    ],
    interviewTips: [
      "Walk start → part → complete → worker; mention abort lifecycle.",
      "For Dropbox, add client-side chunking and hash-based skip.",
    ],
    pitfalls: [
      "No abort — money leak on multipart.",
      "Complete without verifying part count vs declared size.",
      "Storing in-progress bytes on one app pod's disk.",
    ],
    practiceIdeas: [
      "Design TUS-like status API plus S3 multipart under the hood.",
      "Estimate part size for a 4 GB video on 4G with 2% failure per part.",
    ],
    related: [
      "object-storage",
      "dropbox",
      "youtube",
      "image-video-pipelines",
      "idempotency-delivery",
      "stateless-sticky-sessions",
    ],
  },
  {
    slug: "image-video-pipelines",
    track: "hld",
    category: "Files",
    title: "Image and video processing pipelines",
    summary:
      "Async workers that transcode, thumbnail, and package media into CDN-ready variants — never on the upload request thread.",
    depth: "next",
    whyItMatters:
      "Instagram and YouTube are upload + pipeline + serve. The pipeline is a queue of CPU/GPU jobs with idempotent outputs, priority, and poison videos. If you transcode in the API process you fail the interview and the p99.",
    theory: [
      "After a complete upload, you enqueue jobs: validate, virus scan, image resize (WebP/AVIF variants), video transcode (bitrates, codecs), thumbnail, perceptual hash (dupe/abuse), and package HLS/DASH with a manifest. Each job writes objects and updates metadata (status=ready). The user sees processing; the player only gets a URL when enough renditions exist (or adaptive as they land).",
      "Workers are autoscaled on queue depth. GPU for video, CPU for images. Idempotent keys (object version) so retries do not double-write chaos. Dead-letter the poison file (corrupt codec). Priority queues: paid/live vs batch. Store a directed graph of jobs if you have many steps (scan → transcode → package).",
      "Cost is dominated by transcode minutes and storage of variants. Do not keep 20 bitrates of every video forever without a policy. Live streaming is a parallel path (ingest → packager → CDN) with different latency math — see YouTube/Zoom designs.",
    ],
    howItWorks: [
      "Upload complete → message {object_key, user, type}.",
      "Workers write variants to a deterministic prefix; update DB status.",
      "CDN serves variants; API returns the manifest when ready.",
      "Retry with backoff; DLQ corrupt files; alert on age of oldest job.",
      "Lifecycle old renditions when you change codec strategy.",
    ],
    whenToUse: [
      "Any UGC photo/video product.",
      "Document preview generation (PDF → images).",
      "Moderation pipelines that need derived assets.",
    ],
    whenNotToUse: [
      "Do not transcode synchronously in the upload HTTP handler.",
      "Do not generate every possible crop on upload 'just in case.'",
    ],
    tradeoffs: [
      "More variants: better UX and device coverage, storage/CPU cost.",
      "On-the-fly transform: less storage, origin CPU and cache complexity.",
      "Faster presets: quicker 'ready,' worse quality or fewer ladders.",
    ],
    interviewTips: [
      "State machine: uploaded → processing → ready/failed; user can see progress.",
      "Mention abuse: size limits, duration limits, virus/moderation queue.",
    ],
    pitfalls: [
      "Unbounded user-supplied resolution/duration as a DoS.",
      "Non-idempotent workers leaving partial manifests.",
      "Serving the original uncompressed file forever on the hot path.",
    ],
    practiceIdeas: [
      "Draw an Instagram pipeline with 3 image sizes and a video ladder.",
      "Cost a 1-minute 1080p transcode × 10M uploads/day.",
    ],
    related: [
      "chunked-resumable-upload",
      "queues-pubsub-streams",
      "cdn-origin",
      "instagram",
      "youtube",
      "object-storage",
    ],
  },
  {
    slug: "long-poll-ws-sse",
    track: "hld",
    category: "Realtime",
    title: "Long polling, WebSockets, and SSE",
    summary:
      "Three ways to push bytes to a browser or app without the client asking every second — connections, proxies, and fan-out.",
    depth: "core",
    whyItMatters:
      "Chat, presence, live comments, and notifications need a push channel. Picking WS vs SSE vs poll is an HLD staple. The hard part is holding millions of connections and fanning events from a bus to the right sockets.",
    theory: [
      "Short poll is simple and wasteful. Long poll: the server holds HTTP until an event or timeout; the client immediately reconnects. Works everywhere; connection churn and LB timeouts are the tax. Still used as a fallback.",
      "SSE: one-way server→client over HTTP, text/event-stream, automatic retry with Last-Event-ID. Friendly to proxies and HTTP/2 multiplexing. Good for feeds of events, live comments, prices. Not for client→server spam (use HTTP POST alongside).",
      "WebSockets: after upgrade, a bidirectional binary/text pipe. Best for chat, games, collaborative cursors. LBs need idle timeouts and draining. Scale = connection-heavy servers (or specialized gateways) plus a pubsub so the node that holds Alice's socket can get Bob's message. Auth on upgrade and periodically after.",
    ],
    howItWorks: [
      "Terminate connections on a stateful-ish gateway fleet; keep app logic behind.",
      "Subscribe each connection to topics (user, room) on Redis/NATS/Kafka.",
      "Heartbeat; expire dead sockets; handle reconnect with a cursor/seq.",
      "Fallback: SSE or long poll when WS is blocked.",
      "Shard connection nodes; do not require stickiness for HTTP APIs, only for the socket.",
    ],
    whenToUse: [
      "WS: chat, multiplayer, duplex control (Zoom signaling).",
      "SSE: one-way live updates, notifications inbox, comments.",
      "Long poll: constrained clients and fallback.",
    ],
    whenNotToUse: [
      "Do not hold a WS per user just to refresh a daily dashboard — poll or push rarely.",
      "Do not run WS on a server that cannot afford the FDs or that buffers blindly.",
    ],
    tradeoffs: [
      "WS: duplex and efficient, proxy/ops pain.",
      "SSE: simple one-way, no client push on the same socket.",
      "Long poll: portable, higher overhead and latency jitter.",
    ],
    interviewTips: [
      "Draw: clients → WS gateway → pubsub → workers/DB.",
      "Give a connection estimate: 1M online × 1 socket × memory/FD per conn.",
    ],
    pitfalls: [
      "No heartbeat — half-open TCP forever.",
      "Broadcasting by scanning all nodes instead of pubsub topics.",
      "Forgetting authz on each room subscription.",
    ],
    practiceIdeas: [
      "Estimate RAM for 2M idle WS with 8 KB buffers.",
      "Design reconnect: last_event_id catch-up from a short Redis stream.",
    ],
    related: [
      "chat",
      "presence",
      "live-comments",
      "notifications",
      "rest-graphql-grpc",
      "stateless-sticky-sessions",
    ],
  },
  {
    slug: "presence",
    track: "hld",
    category: "Realtime",
    title: "Presence",
    summary:
      "Who is online, idle, or typing — ephemeral state with heartbeats, TTLs, and fan-out that must not become a write storm.",
    depth: "next",
    whyItMatters:
      "WhatsApp green dots look trivial and are a hot-key + fan-out problem. Presence is loss-tolerant and high-churn. Treat it as a specialized ephemeral store, not rows in Postgres updated every 5 seconds.",
    theory: [
      "Each client heartbeats (WS ping or HTTP) every T seconds. The server sets a TTL key `presence:user=online` (Redis) or a gossip entry. If TTL fires, they go offline. Typing indicators are even shorter TTLs. Accuracy is 'good enough'; you accept a few seconds of lag. Multi-device: presence is a set of sessions; the user is online if any session is.",
      "Fan-out: friends want updates. Naive 'on every heartbeat, notify 500 friends' will not survive. Publish presence changes only on transition (online/offline/idle), not on every beat. Subscribers are the users who currently have that profile or chat open — not the entire friend list every time. A pubsub topic per user or a bloom of 'watchers' works.",
      "Scale: shard by user_id. Celebrities: do not fan-out their presence to 50M followers; show 'online' only in active threads or approximate. Persistence is optional (last_seen in DB on a sampled or transition basis). Multi-region: presence is often local; crossing regions is eventual.",
    ],
    howItWorks: [
      "Heartbeat → refresh TTL; on create/expire emit a transition event.",
      "Watchers subscribe to topics for the users they currently view.",
      "Store sessions in Redis hashes; last_seen occasionally to SQL.",
      "Cap typing events (debounce) and drop under load.",
      "Multi-device merge: OR of sessions.",
    ],
    whenToUse: [
      "Chat, collab docs, multiplayer lobbies, support consoles.",
      "Typing and 'seen' as extra ephemeral channels.",
      "Lightweight 'is the courier moving' with a longer TTL.",
    ],
    whenNotToUse: [
      "Do not write last_seen to SQL on every heartbeat at 10M DAU.",
      "Do not broadcast celebrity presence to all followers.",
    ],
    tradeoffs: [
      "Short TTL: accurate offline, more heartbeats and false flaps on bad networks.",
      "Long TTL: fewer writes, ghost online.",
      "Fan-out on transition vs poll last_seen: push vs simpler read path.",
    ],
    interviewTips: [
      "Separate heartbeat path from message path; they have different SLOs.",
      "Say 'TTL in Redis, events on edge transitions, watchers not all friends.'",
    ],
    pitfalls: [
      "Presence rows in the primary DB.",
      "Thundering herd when a popular user comes online.",
      "Clock-based expiry without TTL (app cron cannot keep up).",
    ],
    practiceIdeas: [
      "Design presence for WhatsApp including multi-device and last_seen privacy.",
      "Compute QPS of heartbeats vs transition events for 50M daily online.",
    ],
    related: [
      "presence-service",
      "chat",
      "long-poll-ws-sse",
      "fan-out-write-vs-read",
      "redis-vs-memcached",
      "hot-keys-partitions",
    ],
  },
  {
    slug: "fan-out-write-vs-read",
    track: "hld",
    category: "Realtime",
    title: "Fan-out on write vs fan-out on read",
    summary:
      "Push work to many inboxes when an event happens, or pull and merge when someone looks — the core social/realtime fork.",
    depth: "core",
    whyItMatters:
      "Newsfeed, notifications, live comments, and chat receipts all pick a side (or a hybrid). This is the same idea as the estimates topic, focused on product architecture and celebrity exceptions.",
    theory: [
      "Fan-out on write (push): on a tweet, write a reference into each follower's inbox/cache. Reads are cheap (list inbox). Writes explode with follower count. Storage multiplies. Great for normal users and for notifications to a bounded set (your devices, a small room).",
      "Fan-out on read (pull): store the tweet once; on read, fetch recent posts from followees (or a sample) and merge. Writes are cheap; reads are CPU and cache-heavy. Great for celebrities and for large rooms where most users are not looking.",
      "Hybrid: push for users below a follower threshold; pull for celebrities; cache the merge. Live comments often pull a recent window + subscribe to a stream for the next ones. Chat in a small room can push to online sockets only (not to all historical members' disks).",
    ],
    howItWorks: [
      "Estimate p50 vs p99 fan-out size before you pick.",
      "Push into a per-user cache/queue with a cap (trim old).",
      "Pull with a cached merge and a celebrity skip list.",
      "For realtime, push only to currently connected subscribers.",
      "Make the write path async so the author's HTTP does not wait for 1M writes.",
    ],
    whenToUse: [
      "Push: notifications to devices, small-group chat, normal-user feeds.",
      "Pull: celebrities, huge live rooms, rarely-opened inboxes.",
      "Hybrid: any general social feed.",
    ],
    whenNotToUse: [
      "Do not synchronously push to 10M inboxes on the request.",
      "Do not pull-merge 5000 followees on every mobile scroll with no cache.",
    ],
    tradeoffs: [
      "Push: read latency and simple UX, write/storage blowups.",
      "Pull: cheap writes, heavier reads and ranking at read time.",
      "Hybrid: best practical, more code paths to test.",
    ],
    interviewTips: [
      "Draw both and circle hybrid as the production answer for Twitter-like.",
      "For live comments, 'pull recent + subscribe' is a clean hybrid.",
    ],
    pitfalls: [
      "Unbounded inbox growth.",
      "Pushing to offline users as if they were sockets.",
      "Ranking only at write time then never revising (stale feed).",
    ],
    practiceIdeas: [
      "Pick push/pull/hybrid for feed, notifications, live comments, and group chat.",
      "Size a worker fleet to fan-out a 10M-follower tweet in 30 seconds.",
    ],
    related: [
      "fan-out-read-write-ratio",
      "newsfeed",
      "notifications",
      "live-comments",
      "chat",
      "trending-topics",
    ],
  },
  {
    slug: "unique-ids",
    track: "hld",
    category: "Realtime",
    title: "Unique IDs: UUID, Snowflake, and ticket servers",
    summary:
      "How you mint unique, sometimes sortable IDs without a single global auto-increment bottleneck.",
    depth: "core",
    whyItMatters:
      "URL shorteners, tweets, and chat messages all need IDs. Database auto-increment does not survive multiple primaries. UUID v4 does not sort by time. Snowflake-style IDs are the interview classic — including clock and uniqueness pitfalls.",
    theory: [
      "UUID v4: 122 random bits, collision-safe, no coordination, ugly indexes (random B-tree inserts) and not time-sortable. UUID v7 (and ULID) encode time + randomness — better locality. Fine for many OLTP keys if the engine and UUID version play nice.",
      "Snowflake (Twitter): 64-bit = timestamp + worker id + sequence. Time-sortable, compact, needs unique worker ids and reasonably monotonic clocks. Clock rollback can collide unless you wait or increment a generation. Worker id allocation is a small coordination problem (config, ZooKeeper, or hash of pod IP with care).",
      "Ticket servers (Flickr): a SQL table that hands out ranges (`UPDATE tickets SET n=n+1000`). Simple, can be a hotspot, easy to understand. Range allocators (Leaf, TinyID) cache slabs in app memory. Hi/lo is the same idea. For short URLs you also encode ids in base62. Do not use time-only ids — collisions under concurrency.",
    ],
    howItWorks: [
      "If you have one primary and low write rate, sequences are fine.",
      "If many writers, use UUID v7 or Snowflake with assigned worker ids.",
      "Keep a sequence per worker; block if the clock jumps backward.",
      "For short codes, generate unique ids then encode; handle the (rare) collision.",
      "Never expose incrementing ids if they leak volume or allow enumeration — hash or encrypt the public form if needed.",
    ],
    whenToUse: [
      "Snowflake/ULID: feeds, chat, URL ids, anywhere you sort by time roughly.",
      "UUID: entities that never need sort-by-id and may be created offline.",
      "Ticket ranges: simple services already on SQL.",
    ],
    whenNotToUse: [
      "Do not use a global Redis INCR as the only ID gen without HA and persistence thought.",
      "Do not use wall-clock millis alone as a unique key.",
    ],
    complexity: {
      time: "O(1) per id; coordination only for worker-id assignment",
      space: "64–128 bits per id",
      notes: "Snowflake: ~4096 ids/ms/worker with a 12-bit sequence (classic layout).",
    },
    tradeoffs: [
      "Random UUID: no coord, worse locality and sort.",
      "Snowflake: compact and sortable, clock and worker-id ops.",
      "SQL tickets: obvious, easier to bottleneck and to lose ranges on crash (gaps are OK).",
    ],
    interviewTips: [
      "For URL shortener and Twitter, propose Snowflake or a range allocator; mention clock skew.",
      "Gaps in sequences are not bugs; uniqueness is the invariant.",
    ],
    pitfalls: [
      "Two workers with the same worker id after a bad deploy.",
      "Relying on NTP step-back without a safety pause.",
      "Predictable public ids that let people scrape (use unguessable tokens where needed).",
    ],
    practiceIdeas: [
      "Layout a 64-bit Snowflake and compute max workers and ids/ms.",
      "Compare UUID v4 vs v7 index locality on a large Postgres table.",
    ],
    related: [
      "unique-id-generator",
      "url-shortener",
      "failure-modes",
      "newsfeed",
      "chat",
      "indexes",
    ],
  },
];
