import { diagram, type TopicDiagram } from "./diagrams";

export const CRAFTED: Record<string, TopicDiagram> = {
  "dsa:linear-search": diagram(
    "array",
    "Scan left to right",
    [],
    [],
    "No halves. One finger walks the row until a hit or the end.",
    [
      [["0"], "Check 4 — not 9.", { "0": "i" }],
      [["1"], "Check 1 — not 9.", { "1": "i" }],
      [["2"], "Check 7 — not 9.", { "2": "i" }],
      [["3"], "Check 9 — found. Stop.", { "3": "hit" }],
    ],
    { cells: [4, 1, 7, 9, 2, 8].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:binary-search": diagram(
    "array",
    "Throw away half",
    [],
    [],
    "Sorted row. Mid decides which half can still hold 9. The other half goes grey.",
    [
      [["0", "1", "2", "3", "4", "5", "6"], "lo=0 hi=6 mid=3. 7 < 9 — drop left.", { "0": "lo", "3": "mid", "6": "hi" }],
      [["4", "5", "6"], "lo=4 hi=6 mid=5. 11 > 9 — drop right.", { "4": "lo", "5": "mid", "6": "hi" }],
      [["4"], "lo=hi=4. 9 found.", { "4": "hit" }],
    ],
    { cells: [1, 3, 5, 7, 9, 11, 13].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:binary-search-bounds": diagram(
    "array",
    "First and last hit",
    [],
    [],
    "Same loop, biased shrink. Left-bias finds the first 7; right-bias finds the last.",
    [
      [["0", "1", "2", "3", "4", "5"], "Target 7. Mid 7 — keep going left for first.", { "2": "mid", "0": "lo", "5": "hi" }],
      [["0", "1", "2"], "Still 7 at mid. Shrink hi to mid.", { "1": "mid", "2": "first" }],
      [["2", "3", "4", "5"], "Right-bias: keep going right for last 7.", { "4": "last" }],
    ],
    { cells: [1, 3, 7, 7, 7, 12].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:peak-finding": diagram(
    "array",
    "Walk toward a peak",
    [],
    [],
    "Compare mid with mid+1. The uphill side still has a peak.",
    [
      [["0", "1", "2", "3", "4", "5"], "mid=2 (4) vs 5. Slope goes right — drop left.", { "2": "mid", "3": "mid+1" }],
      [["3", "4", "5"], "mid=4 (8) vs 6. Slope goes left — drop right.", { "4": "mid", "5": "mid+1" }],
      [["3", "4"], "8 ≥ neighbors. Peak.", { "4": "peak" }],
    ],
    { cells: [1, 3, 4, 5, 8, 6].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:search-rotated-array": diagram(
    "array",
    "One sorted half",
    [],
    [],
    "Rotated [4,5,6,7,0,1,2]. One side of mid is sorted — use that to keep or drop.",
    [
      [["0", "1", "2", "3", "4", "5", "6"], "Left of mid is sorted 4..7. Target 0 is not in there.", { "0": "lo", "3": "mid", "6": "hi" }],
      [["4", "5", "6"], "Now [0,1,2]. Ordinary binary search.", { "4": "lo", "5": "mid", "6": "hi" }],
      [["4"], "0 found.", { "4": "hit" }],
    ],
    { cells: [4, 5, 6, 7, 0, 1, 2].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:binary-search-on-answer": diagram(
    "array",
    "Search the answer, not an index",
    [],
    [],
    "The row is possible k values. P(k)=can finish in k days. False prefix, true suffix.",
    [
      [["0", "1", "2", "3", "4", "5"], "k=8. Feasible? No — go right.", { "2": "no" }],
      [["3", "4", "5"], "k=12. Yes — try smaller.", { "3": "yes" }],
      [["3"], "Least true k is 12.", { "3": "ans" }],
    ],
    { cells: ["k=4", "k=6", "k=8", "k=12", "k=16", "k=24"].map((value, i) => ({ id: String(i), value })) },
  ),
  "dsa:two-pointers": diagram(
    "pointers",
    "Two fingers, one pass",
    [],
    [],
    "Sorted pair-sum. Big sum moves R left. Small sum moves L right.",
    [
      [["0", "4"], "1+11=12 too big. Move R.", { "0": "L", "4": "R" }],
      [["0", "3"], "1+7=8 too small. Move L.", { "0": "L", "3": "R" }],
      [["1", "3"], "2+7=9 still small. Move L.", { "1": "L", "3": "R" }],
      [["2", "3"], "4+7=11. Hit or one more step.", { "2": "L", "3": "R" }],
    ],
    { cells: [1, 2, 4, 7, 11].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:sliding-window-fixed": diagram(
    "window",
    "Box of width k",
    [],
    [],
    "k=3. Slide one: drop the left, add the new right. Never rebuild the sum.",
    [
      [["0", "1", "2"], "Window [2,1,5] = 8.", { "0": "L", "2": "R" }],
      [["1", "2", "3"], "Drop 2, add 1 → 7.", { "1": "L", "3": "R" }],
      [["2", "3", "4"], "Drop 1, add 3 → 9. Best.", { "2": "L", "4": "R" }],
    ],
    { cells: [2, 1, 5, 1, 3].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:sliding-window-variable": diagram(
    "window",
    "Grow and shrink",
    [],
    [],
    "Longest window with sum ≤ 7. Expand R; while invalid, move L.",
    [
      [["0", "1"], "Grow: [2,1] = 3. OK.", { "0": "L", "1": "R" }],
      [["0", "1", "2"], "Grow: +5 = 8. Too big.", { "0": "L", "2": "R" }],
      [["1", "2"], "Shrink L. [1,5] = 6. OK.", { "1": "L", "2": "R" }],
      [["1", "2", "3"], "Grow: +1 = 7. Best length 3.", { "1": "L", "3": "R" }],
    ],
    { cells: [2, 1, 5, 1, 3].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:fast-slow-pointers": diagram(
    "list",
    "Turtle and hare",
    [
      ["a", "3", "cell"],
      ["b", "1", "cell"],
      ["c", "4", "cell"],
      ["d", "1", "cell"],
      ["e", "5", "cell"],
    ],
    [
      ["a", "b", "next"],
      ["b", "c", "next"],
      ["c", "d", "next"],
      ["d", "e", "next"],
      ["e", "c", "cycle", "dashed"],
    ],
    "Slow +1, fast +2. They meet inside the cycle. Reset one to head to find the start.",
    [
      [["a", "a"], "Both at head."],
      [["b", "c"], "Slow at 1, fast at 4."],
      [["c", "e"], "Slow at 4, fast at 5."],
      [["d", "d"], "Meet at 1. Cycle exists."],
    ],
  ),
  "dsa:bfs": diagram(
    "graph",
    "Ripples from the start",
    [
      ["A", "A", "actor", 50, 12],
      ["B", "B", "cell", 22, 40],
      ["C", "C", "cell", 78, 40],
      ["D", "D", "cell", 10, 72],
      ["E", "E", "cell", 38, 72],
      ["F", "F", "cell", 78, 72],
    ],
    [
      ["A", "B", "1"],
      ["A", "C", "1"],
      ["B", "D", "1"],
      ["B", "E", "1"],
      ["C", "F", "1"],
    ],
    "Queue holds the frontier. First time you see a node is the hop-shortest path.",
    [
      [["A"], "Queue: A. Dist 0."],
      [["A", "B", "C"], "Pop A. Enqueue B, C. Dist 1."],
      [["A", "B", "C", "D", "E", "F"], "Pop B then C. Enqueue D, E, F. Dist 2."],
    ],
  ),
  "dsa:dfs": diagram(
    "graph",
    "One path to the bottom",
    [
      ["A", "A", "actor", 50, 12],
      ["B", "B", "cell", 22, 40],
      ["C", "C", "cell", 78, 40],
      ["D", "D", "cell", 22, 72],
      ["E", "E", "cell", 78, 72],
    ],
    [
      ["A", "B"],
      ["A", "C"],
      ["B", "D"],
      ["C", "E"],
    ],
    "Stack / recursion. Finish a branch before the sibling. Good for 'exists', not shortest.",
    [
      [["A"], "Start A."],
      [["A", "B"], "Dive A → B."],
      [["A", "B", "D"], "Dive B → D. Dead end."],
      [["A", "B", "D", "C"], "Back to A, take C."],
    ],
  ),
  "dsa:dijkstra": diagram(
    "graph",
    "Cheapest known next",
    [
      ["S", "S", "actor", 12, 50],
      ["A", "A 4", "cell", 40, 22],
      ["B", "B 2", "cell", 40, 78],
      ["T", "T 5", "store", 82, 50],
    ],
    [
      ["S", "A", "4"],
      ["S", "B", "2"],
      ["B", "A", "1"],
      ["A", "T", "1"],
      ["B", "T", "5"],
    ],
    "Min-heap of (dist, node). Relax edges. First pop of T is the shortest weighted path.",
    [
      [["S"], "dist S=0. Heap: S."],
      [["S", "B"], "Pop S. B=2, A=4."],
      [["S", "B", "A"], "Pop B. Relax A via B: 2+1=3. T=7."],
      [["S", "B", "A", "T"], "Pop A. T via A: 3+1=4. Best."],
    ],
  ),
  "dsa:union-find": diagram(
    "union-find",
    "Forest of parents",
    [
      ["1", "1", "cell", 18, 70],
      ["2", "2", "cell", 38, 70],
      ["3", "3", "cell", 58, 70],
      ["4", "4", "cell", 78, 70],
      ["r1", "1", "actor", 28, 28],
      ["r2", "3", "actor", 68, 28],
    ],
    [
      ["1", "r1"],
      ["2", "r1"],
      ["3", "r2"],
      ["4", "r2"],
    ],
    "Find walks to the root. Union links roots (by rank) and path-compresses.",
    [
      [["1", "2", "3", "4"], "Start: each node its own parent."],
      [["1", "2", "r1"], "union(1,2). Root 1."],
      [["3", "4", "r2"], "union(3,4). Root 3."],
      [["r1", "r2"], "find(2)==find(4)? 1≠3. Not connected."],
    ],
  ),
  "dsa:knapsack-01": diagram(
    "dp-table",
    "Take or skip, once",
    [
      ["h0", "c0", "cell"],
      ["h1", "c1", "cell"],
      ["h2", "c2", "cell"],
      ["h3", "c3", "cell"],
      ["h4", "c4", "cell"],
      ["h5", "c5", "cell"],
      ["i0-0", "0", "cell"],
      ["i0-1", "0", "cell"],
      ["i0-2", "0", "cell"],
      ["i0-3", "0", "cell"],
      ["i0-4", "0", "cell"],
      ["i0-5", "0", "cell"],
      ["i1-0", "0", "cell"],
      ["i1-1", "0", "cell"],
      ["i1-2", "3", "cell"],
      ["i1-3", "3", "cell"],
      ["i1-4", "3", "cell"],
      ["i1-5", "3", "cell"],
      ["i2-0", "0", "cell"],
      ["i2-1", "0", "cell"],
      ["i2-2", "3", "cell"],
      ["i2-3", "4", "cell"],
      ["i2-4", "4", "cell"],
      ["i2-5", "7", "cell"],
    ],
    [],
    "Items (w=2,v=3) then (w=3,v=4). Capacity 5. Each item at most once — roll capacity backward.",
    [
      [["i0-0", "i0-1", "i0-2", "i0-3", "i0-4", "i0-5"], "Row 0: no items. All 0."],
      [["i1-2", "i1-3", "i1-4", "i1-5"], "Item 1 (2,3): fill c≥2 with 3."],
      [["i2-3", "i2-5"], "Item 2 (3,4): c=3 → 4; c=5 → 3+4=7. Answer 7."],
    ],
    {
      layout: "grid",
      lanes: [
        { id: "head", label: "cap", nodes: ["h0", "h1", "h2", "h3", "h4", "h5"] },
        { id: "r0", label: "∅", nodes: ["i0-0", "i0-1", "i0-2", "i0-3", "i0-4", "i0-5"] },
        { id: "r1", label: "+(2,3)", nodes: ["i1-0", "i1-1", "i1-2", "i1-3", "i1-4", "i1-5"] },
        { id: "r2", label: "+(3,4)", nodes: ["i2-0", "i2-1", "i2-2", "i2-3", "i2-4", "i2-5"] },
      ],
    },
  ),
  "dsa:coin-change": diagram(
    "array",
    "Fewest coins to make n",
    [],
    [],
    "1-D dp[x] = min coins to make x. Coins 1,3,4. Forward loop — unbounded.",
    [
      [["0"], "dp[0]=0.", { "0": "base" }],
      [["1", "3", "4"], "Coin 1 fills 1..n. Coin 3 then 4 overwrite better.", { "4": "coin" }],
      [["6"], "dp[6]=2 (3+3). Not 1+1+4 if worse.", { "6": "ans" }],
    ],
    { cells: ["0", "1", "2", "1", "1", "2", "2"].map((value, i) => ({ id: String(i), value })) },
  ),
  "dsa:lcs": diagram(
    "dp-table",
    "Two strings, one grid",
    [
      ["e", "LCS", "cell"],
      ["a", "A", "cell"],
      ["b", "B", "cell"],
      ["c", "C", "cell"],
      ["x", "A", "cell"],
      ["y", "C", "cell"],
      ["z", "B", "cell"],
      ["11", "1", "cell"],
      ["12", "1", "cell"],
      ["13", "1", "cell"],
      ["21", "1", "cell"],
      ["22", "1", "cell"],
      ["23", "2", "cell"],
      ["31", "1", "cell"],
      ["32", "2", "cell"],
      ["33", "2", "cell"],
    ],
    [],
    "ACE vs ABC. Match → diagonal +1. Else max(left, up). Answer 2 (A C).",
    [
      [["11"], "A=A. Diagonal 1."],
      [["23"], "C vs C after AB… = 2."],
      [["33"], "Bottom-right is LCS length."],
    ],
    {
      layout: "grid",
      lanes: [
        { id: "r1", label: "A", nodes: ["11", "12", "13"] },
        { id: "r2", label: "C", nodes: ["21", "22", "23"] },
        { id: "r3", label: "E", nodes: ["31", "32", "33"] },
      ],
    },
  ),
  "dsa:lis": diagram(
    "array",
    "Longest increasing tail",
    [],
    [],
    "Patience piles / tails array. 3,1,2,4 → LIS 1,2,4 length 3.",
    [
      [["0"], "3 starts pile 1.", { "0": "tail" }],
      [["1"], "1 replaces 3.", { "1": "tail" }],
      [["1", "2"], "2 extends.", { "2": "tail" }],
      [["1", "2", "3"], "4 extends. Length 3.", { "3": "ans" }],
    ],
    { cells: [3, 1, 2, 4].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:fibonacci-dp": diagram(
    "rec-tree",
    "Tree vs memo row",
    [
      ["f5", "f(5)", "actor"],
      ["f4", "f(4)", "cell"],
      ["f3a", "f(3)", "cell"],
      ["f3b", "f(3)", "cell"],
      ["f2", "f(2)", "cache"],
    ],
    [
      ["f5", "f4"],
      ["f5", "f3a"],
      ["f4", "f3b"],
      ["f4", "f2"],
    ],
    "Naive tree repeats f(3). Bottom-up row [1,1,2,3,5] computes each once.",
    [
      [["f5"], "Ask f(5)."],
      [["f5", "f4", "f3a"], "Two children. f(3) will be asked twice."],
      [["f2"], "Memo: store f(n) so the second call is O(1)."],
    ],
  ),
  "dsa:grid-dp": diagram(
    "dp-table",
    "Only right or down",
    [
      ["a", "1", "cell"],
      ["b", "1", "cell"],
      ["c", "1", "cell"],
      ["d", "1", "cell"],
      ["e", "2", "cell"],
      ["f", "3", "cell"],
      ["g", "1", "cell"],
      ["h", "3", "cell"],
      ["i", "6", "cell"],
    ],
    [],
    "Unique paths on a 3×3. Cell = from-left + from-above.",
    [
      [["a", "b", "c", "d", "g"], "First row and col are 1."],
      [["e"], "1+1=2."],
      [["i"], "3+3=6 paths to the corner."],
    ],
    {
      layout: "grid",
      lanes: [
        { id: "r0", label: "r0", nodes: ["a", "b", "c"] },
        { id: "r1", label: "r1", nodes: ["d", "e", "f"] },
        { id: "r2", label: "r2", nodes: ["g", "h", "i"] },
      ],
    },
  ),
  "dsa:two-sum": diagram(
    "buckets",
    "Need and seen",
    [
      ["n0", "2", "cell"],
      ["n1", "7", "cell"],
      ["n2", "11", "cell"],
      ["n3", "15", "cell"],
      ["m7", "need 7", "cache"],
      ["hit", "7 @ i=1", "store"],
    ],
    [
      ["n0", "m7", "9-2"],
      ["n1", "hit", "found"],
    ],
    "Walk once. Map value→index. If target-x is already in the map, return the pair.",
    [
      [["n0", "m7"], "See 2. Store need 7."],
      [["n1", "hit"], "See 7. Need is waiting. Pair (0,1)."],
    ],
  ),
  "dsa:kadane": diagram(
    "array",
    "Best ending here",
    [],
    [],
    "At each i: extend the streak or restart. Track global max.",
    [
      [["0"], "best = 2.", { "0": "cur" }],
      [["1"], "2 + (−3) = −1 < −3? Restart −3. Global still 2.", { "1": "cur" }],
      [["2"], "−3+4=1. Take 4. Global 4.", { "2": "cur" }],
      [["3"], "4+(−1)=3. Keep. Global 4.", { "3": "cur" }],
      [["4"], "3+5=8. Global 8.", { "4": "ans" }],
    ],
    { cells: [2, -3, 4, -1, 5].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:prefix-sum": diagram(
    "array",
    "Running totals",
    [],
    [],
    "pref[i] = a[0]+…+a[i]. Range [L,R] is pref[R]−pref[L−1].",
    [
      [["0"], "pref 2.", { "0": "p" }],
      [["1"], "2+1=3.", { "1": "p" }],
      [["3"], "Query [1,3] = 8−2 = 6.", { "1": "L", "3": "R" }],
    ],
    { cells: ["2", "3", "7", "8", "10"].map((value, i) => ({ id: String(i), value })) },
  ),
  "dsa:merge-sort": diagram(
    "bars",
    "Split, then zipper",
    [
      ["a", "4", "cell"],
      ["b", "1", "cell"],
      ["c", "3", "cell"],
      ["d", "2", "cell"],
    ],
    [],
    "Halves until one element, then merge two sorted runs.",
    [
      [["a", "b", "c", "d"], "Unsorted 4 1 3 2."],
      [["b", "a", "d", "c"], "Sorted pairs: 1,4 and 2,3."],
      [["b", "d", "c", "a"], "Zipper: 1,2,3,4."],
    ],
    { cells: [4, 1, 3, 2].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:quick-sort": diagram(
    "bars",
    "Pivot and partition",
    [
      ["a", "3", "cell"],
      ["b", "1", "cell"],
      ["c", "4", "cell"],
      ["d", "2", "cell"],
    ],
    [],
    "Pick a pivot. < pivot left, > pivot right. Recurse both sides.",
    [
      [["c"], "Pivot 4."],
      [["a", "b", "d", "c"], "Partition: 3,1,2 | 4."],
      [["b", "d", "a", "c"], "Recurse left → 1,2,3,4."],
    ],
    { cells: [3, 1, 4, 2].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:heapify": diagram(
    "heap",
    "Sift down to a heap",
    [
      ["r", "2", "actor", 50, 16],
      ["l", "8", "cell", 28, 48],
      ["ri", "5", "cell", 72, 48],
      ["ll", "3", "cell", 16, 80],
      ["lr", "4", "cell", 40, 80],
    ],
    [
      ["r", "l"],
      ["r", "ri"],
      ["l", "ll"],
      ["l", "lr"],
    ],
    "Parent must beat both children. Swap 2 with 8, then again if needed.",
    [
      [["r"], "2 is smaller than 8 and 5."],
      [["l", "r"], "Swap with larger child 8."],
      [["l"], "Heap property restored at the root."],
    ],
  ),
  "dsa:top-k": diagram(
    "heap",
    "A heap of size k",
    [
      ["h1", "5", "actor", 50, 18],
      ["h2", "7", "cell", 28, 52],
      ["h3", "9", "cell", 72, 52],
      ["x", "4", "queue", 50, 86],
    ],
    [
      ["h1", "h2"],
      ["h1", "h3"],
    ],
    "Min-heap of the best k. Next item 4 < root 5 — ignore. 10 would pop 5 and push 10.",
    [
      [["h1", "h2", "h3"], "Heap holds 5,7,9. k=3."],
      [["x"], "See 4. Smaller than min — discard."],
    ],
  ),
  "dsa:trie": diagram(
    "trie",
    "Shared prefixes",
    [
      ["root", "·", "actor", 50, 12],
      ["c", "c", "cell", 50, 36],
      ["a", "a", "cell", 32, 60],
      ["t", "t", "store", 32, 84],
      ["ar", "ar", "cell", 68, 60],
      ["s", "s", "store", 68, 84],
    ],
    [
      ["root", "c"],
      ["c", "a"],
      ["a", "t", "cat"],
      ["c", "ar"],
      ["ar", "s", "cars"],
    ],
    "cat and cars share c. End marks sit on t and s — not a flat hashmap of words.",
    [
      [["root", "c"], "First letter c."],
      [["c", "a", "t"], "Spell cat. Mark end."],
      [["c", "ar", "s"], "cars branches after c."],
    ],
  ),
  "dsa:tree-traversals": diagram(
    "tree",
    "Pre / in / post",
    [
      ["n", "8", "actor", 50, 16],
      ["l", "3", "cell", 28, 50],
      ["r", "10", "cell", 72, 50],
      ["ll", "1", "cell", 16, 82],
      ["lr", "6", "cell", 40, 82],
    ],
    [
      ["n", "l"],
      ["n", "r"],
      ["l", "ll"],
      ["l", "lr"],
    ],
    "Pre: node, left, right. In: left, node, right. Post: children, then node.",
    [
      [["n"], "Pre starts at 8."],
      [["n", "l", "ll"], "Then left subtree 3,1…"],
      [["ll", "l", "lr", "n", "r"], "In-order of a BST is sorted: 1,3,6,8,10."],
    ],
  ),
  "dsa:reverse-linked-list": diagram(
    "list",
    "Three pointers",
    [
      ["a", "1", "cell"],
      ["b", "2", "cell"],
      ["c", "3", "cell"],
      ["d", "4", "cell"],
    ],
    [
      ["a", "b"],
      ["b", "c"],
      ["c", "d"],
    ],
    "prev, cur, next. Flip cur.next = prev. Slide the triple.",
    [
      [["a"], "prev=null, cur=1."],
      [["a", "b"], "1 → null. cur=2."],
      [["b", "a"], "2 → 1 → null."],
      [["d", "c", "b", "a"], "4 → 3 → 2 → 1."],
    ],
  ),
  "dsa:valid-parentheses": diagram(
    "stack",
    "Push open, pop match",
    [
      ["s0", "(", "cell"],
      ["s1", "[", "cell"],
      ["s2", "{", "cell"],
    ],
    [],
    "Opens go on the stack. A close must match the top or the string is invalid.",
    [
      [["s0"], "See (. Push."],
      [["s0", "s1"], "See [. Push."],
      [["s0"], "See ]. Pop [. Match."],
    ],
  ),
  "dsa:next-greater-element": diagram(
    "stack",
    "Monotonic decreasing",
    [
      ["a", "2", "cell"],
      ["b", "1", "cell"],
      ["c", "5", "cell"],
      ["d", "3", "cell"],
    ],
    [],
    "Walk left→right. Pop anything smaller than a[i] — a[i] is their next greater.",
    [
      [["a"], "Stack: 2."],
      [["a", "b"], "1 < 2. Push 1."],
      [["c"], "5 pops 1 then 2. Next greater of both is 5."],
    ],
  ),
  "dsa:kmp": diagram(
    "array",
    "Prefix table, no restart",
    [],
    [],
    "Pattern aaba. lps[i] = longest prefix that is a suffix. Mismatch jumps to lps.",
    [
      [["0", "1"], "aa — lps 0,1.", { "1": "lps=1" }],
      [["2"], "aab — b breaks. lps=0.", { "2": "lps=0" }],
      [["3"], "aaba — last a matches prefix. lps=1.", { "3": "lps=1" }],
    ],
    { cells: ["a", "a", "b", "a"].map((value, i) => ({ id: String(i), value })) },
  ),
  "dsa:topo-sort-kahn": diagram(
    "graph",
    "Zero-indegree queue",
    [
      ["A", "A0", "actor", 16, 28],
      ["B", "B1", "cell", 50, 28],
      ["C", "C1", "cell", 50, 72],
      ["D", "D2", "store", 84, 50],
    ],
    [
      ["A", "B"],
      ["A", "C"],
      ["B", "D"],
      ["C", "D"],
    ],
    "Queue nodes with indegree 0. Pop, decrement neighbors. Order is a valid topo.",
    [
      [["A"], "Only A has indegree 0."],
      [["A", "B", "C"], "Remove A. B and C fall to 0."],
      [["A", "B", "C", "D"], "Then D. Unique-ish order A, B, C, D."],
    ],
  ),
  "dsa:islands": diagram(
    "dp-table",
    "Flood each land",
    [
      ["a", "1", "cell"],
      ["b", "1", "cell"],
      ["c", "0", "cell"],
      ["d", "0", "cell"],
      ["e", "1", "cell"],
      ["f", "0", "cell"],
      ["g", "1", "cell"],
      ["h", "0", "cell"],
      ["i", "1", "cell"],
    ],
    [],
    "Scan the grid. On a 1, BFS/DFS mark the whole island and increment the count.",
    [
      [["a", "b"], "Island 1: flood the top-left 1s."],
      [["e"], "Island 2: lonely 1."],
      [["g", "i"], "Island 3: bottom 1s if connected — here two more scans."],
    ],
    {
      layout: "grid",
      lanes: [
        { id: "r0", label: "", nodes: ["a", "b", "c"] },
        { id: "r1", label: "", nodes: ["d", "e", "f"] },
        { id: "r2", label: "", nodes: ["g", "h", "i"] },
      ],
    },
  ),
  "hld:url-shortener": diagram(
    "split",
    "Mint vs redirect",
    [
      ["cw", "Client", "client"],
      ["post", "POST /urls", "service"],
      ["id", "Snowflake→62", "worker"],
      ["dbw", "SQL insert", "store"],
      ["cr", "Client", "client"],
      ["get", "GET /code", "edge"],
      ["redis", "Redis", "cache"],
      ["dbr", "SQL", "store"],
      ["go", "302", "edge"],
    ],
    [
      ["cw", "post", "mint"],
      ["post", "id"],
      ["id", "dbw", "write"],
      ["cr", "get", "read"],
      ["get", "redis"],
      ["redis", "dbr", "miss"],
      ["dbr", "go"],
    ],
    "Writes mint a unique code. Reads hit Redis, then SQL, then 302. Analytics stay off this path.",
    [
      [["cw", "post", "id", "dbw"], "Write: mint code, persist, return short URL."],
      [["cr", "get", "redis"], "Read: cache hit — 302 immediately."],
      [["get", "dbr", "go"], "Cache miss: SQL, fill Redis, 302."],
    ],
    {
      lanes: [
        { id: "w", label: "POST mint", nodes: ["cw", "post", "id", "dbw"] },
        { id: "r", label: "GET redirect", nodes: ["cr", "get", "redis", "dbr", "go"] },
      ],
    },
  ),
  "hld:cap-theorem": diagram(
    "cut",
    "Partition, then pick",
    [
      ["a", "Replica A", "store", 22, 40],
      ["b", "Replica B", "store", 78, 40],
      ["cp", "CP: refuse write", "policy", 22, 78],
      ["ap", "AP: accept & repair", "policy", 78, 78],
    ],
    [
      ["a", "b", "partition", "cut"],
      ["a", "cp"],
      ["b", "ap"],
    ],
    "The link is cut. You either stop taking writes (CP) or take writes that may conflict (AP).",
    [
      [["a", "b"], "Healthy: both replicas talk."],
      [["a", "b"], "Partition: the cable is gone. P is forced."],
      [["cp"], "Money, unique alias, seat hold — fail closed."],
      [["ap"], "Likes, ticks, typing — stay up, merge later."],
    ],
  ),
  "hld:consistent-hashing": diagram(
    "ring",
    "A ring, not a table",
    [
      ["s1", "S1", "store", 50, 12],
      ["s2", "S2", "store", 88, 50],
      ["s3", "S3", "store", 50, 88],
      ["s4", "S4", "store", 12, 50],
      ["k1", "kA", "cell", 70, 22],
      ["k2", "kB", "cell", 78, 70],
    ],
    [
      ["k1", "s2", "clock"],
      ["k2", "s3", "clock"],
    ],
    "Hash servers and keys onto a circle. Walk clockwise to the next server. Add S5 — only nearby keys move.",
    [
      [["s1", "s2", "s3", "s4"], "Servers sit on the ring."],
      [["k1", "s2"], "kA walks clockwise to S2."],
      [["k2", "s3"], "kB lands on S3."],
    ],
  ),
  "hld:kafka-sqs-rabbit": diagram(
    "fanout",
    "Produce, partition, consume",
    [
      ["p1", "Producer A", "client"],
      ["p2", "Producer B", "client"],
      ["t0", "P0", "queue"],
      ["t1", "P1", "queue"],
      ["t2", "P2", "queue"],
      ["c1", "Consumer 1", "worker"],
      ["c2", "Consumer 2", "worker"],
    ],
    [
      ["p1", "t0", "key"],
      ["p2", "t1"],
      ["t0", "c1"],
      ["t1", "c2"],
      ["t2", "c1"],
    ],
    "Topic split into partitions. A consumer group splits partitions. Order holds inside a partition.",
    [
      [["p1", "p2"], "Producers append."],
      [["t0", "t1", "t2"], "Broker keeps partitions."],
      [["c1", "c2"], "Group members each own some partitions."],
    ],
  ),
  "hld:queues-pubsub-streams": diagram(
    "compare",
    "Three async shapes",
    [
      ["q", "Queue", "queue"],
      ["qw", "One worker", "worker"],
      ["pub", "Pub/sub", "service"],
      ["s1", "Sub A", "worker"],
      ["s2", "Sub B", "worker"],
      ["st", "Stream", "store"],
      ["r", "Replay", "client"],
    ],
    [
      ["q", "qw", "compete"],
      ["pub", "s1", "fan-out"],
      ["pub", "s2"],
      ["st", "r", "offset"],
    ],
    "Queue: compete for a job. Pub/sub: everyone gets a copy. Stream: log + offset, replayable.",
    [
      [["q", "qw"], "Queue — one consumer wins the message."],
      [["pub", "s1", "s2"], "Pub/sub — both subscribers fire."],
      [["st", "r"], "Stream — read from offset 42 again."],
    ],
    {
      lanes: [
        { id: "a", label: "Queue", nodes: ["q", "qw"] },
        { id: "b", label: "Pub/sub", nodes: ["pub", "s1", "s2"] },
        { id: "c", label: "Stream", nodes: ["st", "r"] },
      ],
    },
  ),
  "hld:newsfeed": diagram(
    "fanout",
    "Push most, pull celebrities",
    [
      ["post", "New post", "client"],
      ["f1", "Follower cache", "cache"],
      ["f2", "Follower cache", "cache"],
      ["f3", "Follower cache", "cache"],
      ["celeb", "Celeb timeline", "store"],
      ["me", "My feed merge", "service"],
    ],
    [
      ["post", "f1", "write"],
      ["post", "f2", "write"],
      ["post", "f3", "write"],
      ["celeb", "me", "read"],
    ],
    "Normal users: fan-out on write into follower caches. Celebrities: pull at read and merge.",
    [
      [["post", "f1", "f2", "f3"], "Fan-out on write for normal follower counts."],
      [["celeb", "me"], "50M followers — do not write 50M rows. Pull at read."],
    ],
  ),
  "hld:chat": diagram(
    "flow",
    "Socket, then persist, then push",
    [
      ["phone", "Phone", "client"],
      ["ws", "WS gateway", "edge"],
      ["chat", "Chat svc", "service"],
      ["log", "Message log", "store"],
      ["push", "Push / other device", "queue"],
    ],
    [
      ["phone", "ws"],
      ["ws", "chat"],
      ["chat", "log", "ack after write"],
      ["chat", "push"],
    ],
    "Connections live on a gateway. Persist first, then fan-out to online devices.",
    [
      [["phone", "ws"], "WebSocket stays open."],
      [["chat", "log"], "Persist, then ack 'sent'."],
      [["push"], "Online devices get the event. Offline waits."],
    ],
  ),
  "hld:uber": diagram(
    "mesh",
    "Geo ping, then offer",
    [
      ["rider", "Rider", "client"],
      ["match", "Matching", "service"],
      ["geo", "S2 / GEO", "cache"],
      ["drv", "Driver ping", "actor"],
      ["trip", "Trip lock", "store"],
    ],
    [
      ["drv", "geo", "location"],
      ["rider", "match"],
      ["match", "geo", "nearby"],
      ["match", "trip", "offer TTL"],
    ],
    "Drivers stream cells. A request queries nearby supply and offers one driver at a time.",
    [
      [["drv", "geo"], "Location ingest, not the match path."],
      [["rider", "match", "geo"], "Query nearby cells."],
      [["trip"], "Lock the trip so two drivers do not win."],
    ],
  ),
  "hld:replication": diagram(
    "split",
    "Primary, then replicas",
    [
      ["w", "Write", "client"],
      ["p", "Primary", "store"],
      ["r1", "Replica", "store"],
      ["r2", "Replica", "store"],
      ["rd", "Read", "client"],
    ],
    [
      ["w", "p"],
      ["p", "r1", "sync or async"],
      ["p", "r2"],
      ["rd", "r1"],
    ],
    "Writes land on a primary. Replicas follow. Sync = safer, slower. Async = faster, stale reads.",
    [
      [["w", "p"], "Write on primary."],
      [["p", "r1", "r2"], "Ship the log."],
      [["rd", "r1"], "Reads may be stale if async."],
    ],
    {
      lanes: [
        { id: "wr", label: "Write", nodes: ["w", "p"] },
        { id: "rep", label: "Replicate", nodes: ["r1", "r2"] },
        { id: "rd", label: "Read", nodes: ["rd"] },
      ],
    },
  ),
  "hld:sharding": diagram(
    "buckets",
    "Key → shard",
    [
      ["k", "user_id", "client"],
      ["h", "hash % N", "service"],
      ["s0", "Shard 0", "store"],
      ["s1", "Shard 1", "store"],
      ["s2", "Shard 2", "store"],
    ],
    [
      ["k", "h"],
      ["h", "s1", "slot 1"],
    ],
    "Range, hash, or directory. Hot keys stay hot — they do not split themselves.",
    [
      [["k", "h"], "Pick a shard key."],
      [["s0", "s1", "s2"], "Each shard is its own primary."],
      [["s1"], "This user always lands on shard 1."],
    ],
  ),
  "hld:cache-patterns": diagram(
    "flow",
    "Aside, then stampede guard",
    [
      ["app", "App", "service"],
      ["c", "Cache", "cache"],
      ["db", "DB", "store"],
      ["lock", "Single-flight", "policy"],
    ],
    [
      ["app", "c", "get"],
      ["c", "db", "miss"],
      ["db", "c", "fill"],
      ["lock", "db", "one miss"],
    ],
    "Cache-aside: app owns the get/fill. A lock or early TTL jitter stops a stampede.",
    [
      [["app", "c"], "Hit — return."],
      [["app", "db", "c"], "Miss — load DB, fill."],
      [["lock"], "Many misses: only one walks to DB."],
    ],
  ),
  "hld:load-balancers": diagram(
    "fanin",
    "Many sockets, one VIP",
    [
      ["c1", "Client", "client"],
      ["c2", "Client", "client"],
      ["c3", "Client", "client"],
      ["lb", "L4 / L7 LB", "edge"],
      ["a1", "App A", "service"],
      ["a2", "App B", "service"],
    ],
    [
      ["c1", "lb"],
      ["c2", "lb"],
      ["c3", "lb"],
      ["lb", "a1", "rr / least-conn"],
      ["lb", "a2"],
    ],
    "L4: packets / connections. L7: path, cookie, gRPC. Health checks pull bad apps out.",
    [
      [["c1", "c2", "c3", "lb"], "VIP terminates the clients."],
      [["lb", "a1", "a2"], "Pick a healthy backend."],
    ],
  ),
  "hld:rate-limiting": diagram(
    "decision",
    "Tokens, then allow or 429",
    [
      ["req", "Request", "client"],
      ["b", "Token bucket", "policy"],
      ["ok", "Allow", "service"],
      ["no", "429", "cut"],
    ],
    [
      ["req", "b"],
      ["b", "ok", "token"],
      ["b", "no", "empty"],
    ],
    "Bucket refills at rate r. A request spends a token or gets 429. Sliding window is the other sketch.",
    [
      [["req", "b"], "Arrive at the bucket."],
      [["ok"], "Token left — pass."],
      [["no"], "Empty — 429 and Retry-After."],
    ],
  ),
  "hld:sql-vs-nosql": diagram(
    "compare",
    "Access pattern picks the store",
    [
      ["sql", "SQL", "store"],
      ["rel", "Joins, txns", "service"],
      ["no", "NoSQL / KV", "store"],
      ["kv", "Key + scan", "cache"],
    ],
    [
      ["sql", "rel"],
      ["no", "kv"],
    ],
    "SQL when you need relations and transactions. KV when the key is the query.",
    [
      [["sql", "rel"], "Checkout, ledger, unique alias — SQL."],
      [["no", "kv"], "Session, cache, wide fan-out — KV."],
    ],
    {
      lanes: [
        { id: "s", label: "SQL", nodes: ["sql", "rel"] },
        { id: "n", label: "NoSQL", nodes: ["no", "kv"] },
      ],
    },
  ),
  "hld:monolith-vs-microservices": diagram(
    "compare",
    "One deploy vs many",
    [
      ["mono", "Modular monolith", "service"],
      ["db", "One DB", "store"],
      ["m1", "Orders", "service"],
      ["m2", "Billing", "service"],
      ["q", "Events", "queue"],
    ],
    [
      ["mono", "db"],
      ["m1", "q"],
      ["q", "m2"],
    ],
    "Start modular in one process. Split when a team or scale axis forces a network boundary.",
    [
      [["mono", "db"], "One deploy, in-process calls."],
      [["m1", "q", "m2"], "Split: async events, separate fail."],
    ],
  ),
  "lld:parking-lot": diagram(
    "tree",
    "Lot owns floors owns spots",
    [
      ["lot", "ParkingLot", "class", 50, 12],
      ["f1", "Floor 1", "class", 28, 40],
      ["f2", "Floor 2", "class", 72, 40],
      ["s1", "Spot A", "cell", 16, 68],
      ["s2", "Spot B", "cell", 40, 68],
      ["s3", "Spot C", "cell", 72, 68],
      ["t", "Ticket", "store", 28, 92],
      ["fee", "FeePolicy", "iface", 72, 92],
    ],
    [
      ["lot", "f1"],
      ["lot", "f2"],
      ["f1", "s1"],
      ["f1", "s2"],
      ["f2", "s3"],
      ["s1", "t", "occupy"],
      ["t", "fee", "quote"],
    ],
    "Aggregate is the lot. occupy() is the invariant. Fees are a strategy, not a switch in unpark.",
    [
      [["lot", "f1", "f2"], "Lot → floors → spots."],
      [["s1", "t"], "find + occupy atomically → ticket."],
      [["fee"], "Weekend rate = new FeePolicy. park() stays."],
    ],
  ),
  "lld:elevator": diagram(
    "shaft",
    "Car, floors, request queue",
    [
      ["f5", "5", "cell"],
      ["f4", "4", "cell"],
      ["f3", "3 car", "actor"],
      ["f2", "2", "cell"],
      ["f1", "1", "cell"],
      ["q", "5↑  8  2↓", "queue"],
      ["idle", "Idle", "state"],
      ["move", "Moving", "state"],
      ["open", "Door", "state"],
    ],
    [
      ["idle", "move"],
      ["move", "open"],
      ["open", "idle"],
    ],
    "Each car is a state machine. A scheduler (strategy) assigns hall calls. SCAN is not hardcoded in the car.",
    [
      [["f3", "q"], "Car at 3. Queue: 5↑, 8, 2↓."],
      [["move", "f5"], "Moving up toward 5."],
      [["open"], "Arrive, door, clear stop, recompute direction."],
    ],
  ),
  "lld:strategy-pattern": diagram(
    "classes",
    "Swap the algorithm",
    [
      ["ctx", "Checkout", "class"],
      ["pol", "Payment", "iface"],
      ["a", "Card", "policy"],
      ["b", "UPI", "policy"],
    ],
    [
      ["ctx", "pol", "charge()"],
      ["a", "pol", "implements"],
      ["b", "pol", "implements"],
    ],
    "Context holds an interface. Card and UPI are two classes. No switch in checkout.",
    [
      [["ctx", "pol"], "Checkout calls payment.charge."],
      [["a"], "Card is one brain."],
      [["b"], "UPI is another. Add Wallet the same way."],
    ],
  ),
  "lld:observer-pattern": diagram(
    "fanout",
    "Subject notifies listeners",
    [
      ["sub", "Subject / ticker", "class"],
      ["ch", "Chart", "actor"],
      ["al", "Alert", "actor"],
      ["log", "Log", "actor"],
    ],
    [
      ["sub", "ch", "notify"],
      ["sub", "al", "notify"],
      ["sub", "log", "notify"],
    ],
    "State changes once. Chart, Alert, Log each react. Subscribe/unsubscribe without editing Subject.",
    [
      [["sub"], "Price updates."],
      [["ch", "al", "log"], "Each observer gets the event."],
    ],
  ),
  "lld:singleton-pattern": diagram(
    "decision",
    "One instance — usually a smell",
    [
      ["new", "new Logger()", "cut"],
      ["get", "Logger.get()", "policy"],
      ["one", "Shared instance", "store"],
    ],
    [
      ["new", "one", "many copies"],
      ["get", "one", "one copy"],
    ],
    "Hide the constructor. Everyone gets the same object. Hard to test — prefer DI unless it is a real process singleton.",
    [
      [["new"], "Three news → three loggers. Lost lines."],
      [["get", "one"], "get() always returns the same."],
    ],
  ),
  "lld:factory-method": diagram(
    "classes",
    "Creator defers the class",
    [
      ["c", "Factory", "iface"],
      ["a", "CarFactory", "class"],
      ["b", "BikeFactory", "class"],
      ["p", "Vehicle", "iface"],
    ],
    [
      ["a", "c"],
      ["b", "c"],
      ["a", "p", "create()"],
    ],
    "Caller asks a factory for a Vehicle. New vehicle type = new factory, not a growing switch.",
    [
      [["c", "p"], "Interface in, product out."],
      [["a", "b"], "Two creators. Add TruckFactory later."],
    ],
  ),
  "lld:decorator-pattern": diagram(
    "layers",
    "Wrap, do not subclass",
    [
      ["core", "Stream", "iface"],
      ["buf", "Buffered", "class"],
      ["zip", "Gzip", "class"],
      ["app", "Caller", "actor"],
    ],
    [
      ["app", "zip"],
      ["zip", "buf"],
      ["buf", "core"],
    ],
    "Same interface at every layer. Add behavior by wrapping, not by a subclass explosion.",
    [
      [["app", "zip"], "Caller talks to GzipStream."],
      [["zip", "buf", "core"], "Each wrapper forwards."],
    ],
  ),
  "lld:state-pattern": diagram(
    "states",
    "The object changes kind",
    [
      ["idle", "Idle", "state"],
      ["move", "Moving", "state"],
      ["open", "Open", "state"],
      ["ctx", "Car", "class"],
    ],
    [
      ["idle", "move", "hall call"],
      ["move", "open", "arrive"],
      ["open", "idle", "close"],
      ["ctx", "idle", "holds"],
    ],
    "State objects implement the same events. The car delegates. Adding Maintenance is a new class.",
    [
      [["idle"], "Idle ignores car-calls except to start."],
      [["move"], "Moving queues stops."],
      [["open"], "Open starts a door timer."],
    ],
  ),
  "lld:splitwise": diagram(
    "classes",
    "Ledger, then balances",
    [
      ["exp", "Expense", "class"],
      ["sp", "Split", "class"],
      ["led", "Ledger", "service"],
      ["bal", "Balances", "store"],
      ["sim", "Simplify", "policy"],
    ],
    [
      ["exp", "sp", "sums to total"],
      ["led", "exp", "append"],
      ["led", "bal", "project"],
      ["sim", "bal", "optional"],
    ],
    "Store expenses. Balances are a projection. Simplify is a graph algorithm, not a cell mutate.",
    [
      [["exp", "sp"], "Splits must sum to the total."],
      [["led", "bal"], "apply() then recompute."],
      [["sim"], "Min-cash-flow is a later policy."],
    ],
  ),
  "lld:producer-consumer": diagram(
    "flow",
    "Bounded buffer",
    [
      ["p", "Producer", "actor"],
      ["q", "Blocking queue", "queue"],
      ["c", "Consumer", "worker"],
    ],
    [
      ["p", "q", "put"],
      ["q", "c", "take"],
    ],
    "Queue capacity is the backpressure. Full → producer waits. Empty → consumer waits.",
    [
      [["p", "q"], "put blocks if full."],
      [["q", "c"], "take blocks if empty."],
    ],
  ),
  "lld:hexagonal-architecture": diagram(
    "layers",
    "Domain in the middle",
    [
      ["ui", "HTTP / UI", "edge"],
      ["app", "Use case", "service"],
      ["dom", "Domain", "class"],
      ["db", "SQL adapter", "store"],
      ["pay", "Pay adapter", "policy"],
    ],
    [
      ["ui", "app"],
      ["app", "dom"],
      ["app", "db"],
      ["app", "pay"],
    ],
    "Domain does not import SQL. Adapters implement ports. Tests fake the ports.",
    [
      [["dom"], "Invariants live here."],
      [["app", "db", "pay"], "Ports point out."],
    ],
  ),
  "lld:solid-ocp": diagram(
    "classes",
    "Closed to edits, open to types",
    [
      ["svc", "ParkService", "class"],
      ["fee", "FeePolicy", "iface"],
      ["h", "Hourly", "policy"],
      ["w", "Weekend", "policy"],
    ],
    [
      ["svc", "fee"],
      ["h", "fee"],
      ["w", "fee"],
    ],
    "Adding weekend rates must not rewrite unpark(). New class, same interface.",
    [
      [["svc", "fee"], "Service already talks to a policy."],
      [["w"], "New variant = new class."],
    ],
  ),
};
