import { diagram, type TopicDiagram } from "./diagrams";

export const CRAFTED: Record<string, TopicDiagram> = {
  "dsa:linear-search": diagram(
    "array",
    "Scan left to right",
    [],
    [],
    "No halves. One finger walks the row until a hit or the end.",
    [
      [["0"], "Check 4 — not 9.", { "0": "i" }],
      [["1"], "Check 1 — not 9.", { "1": "i" }],
      [["2"], "Check 7 — not 9.", { "2": "i" }],
      [["3"], "Check 9 — found. Stop.", { "3": "hit" }],
    ],
    { cells: [4, 1, 7, 9, 2, 8].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:binary-search": diagram(
    "array",
    "Throw away half",
    [],
    [],
    "Find 9. Mid decides which sorted half can still hold it.",
    [
      [["0", "1", "2", "3", "4", "5", "6"], "mid=7 < 9. Drop left half.", { "0": "lo", "3": "mid", "6": "hi" }],
      [["4", "5", "6"], "mid=11 > 9. Drop right half.", { "4": "lo", "5": "mid", "6": "hi" }],
      [["4"], "lo=hi. 9 found.", { "4": "hit" }],
    ],
    { cells: [1, 3, 5, 7, 9, 11, 13].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:binary-search-bounds": diagram(
    "array",
    "First and last hit",
    [],
    [],
    "Same loop, biased shrink. Left-bias finds the first 7; right-bias finds the last.",
    [
      [["0", "1", "2", "3", "4", "5"], "Target 7. Mid 7 — keep going left for first.", { "2": "mid", "0": "lo", "5": "hi" }],
      [["0", "1", "2"], "Still 7 at mid. Shrink hi to mid.", { "1": "mid", "2": "first" }],
      [["2", "3", "4", "5"], "Right-bias: keep going right for last 7.", { "4": "last" }],
    ],
    { cells: [1, 3, 7, 7, 7, 12].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:peak-finding": diagram(
    "array",
    "Walk toward a peak",
    [],
    [],
    "Compare mid with mid+1. The uphill side still has a peak.",
    [
      [["0", "1", "2", "3", "4", "5"], "mid=2 (4) vs 5. Slope goes right — drop left.", { "2": "mid", "3": "mid+1" }],
      [["3", "4", "5"], "mid=4 (8) vs 6. Slope goes left — drop right.", { "4": "mid", "5": "mid+1" }],
      [["3", "4"], "8 ≥ neighbors. Peak.", { "4": "peak" }],
    ],
    { cells: [1, 3, 4, 5, 8, 6].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:search-rotated-array": diagram(
    "array",
    "One sorted half",
    [],
    [],
    "Rotated 7|0. One side of mid is sorted — keep or drop that half.",
    [
      [["0", "1", "2", "3", "4", "5", "6"], "Left 4..7 is sorted. 0 is not there.", { "0": "lo", "3": "mid", "6": "hi" }],
      [["4", "5", "6"], "Keep [0,1,2]. mid=1.", { "4": "lo", "5": "mid", "6": "hi" }],
      [["4"], "0 found.", { "4": "hit" }],
    ],
    { cells: [4, 5, 6, 7, 0, 1, 2].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:binary-search-on-answer": diagram(
    "array",
    "Search the answer, not an index",
    [],
    [],
    "The row is possible k values. P(k)=can finish in k days. False prefix, true suffix.",
    [
      [["0", "1", "2", "3", "4", "5"], "k=8. Feasible? No — go right.", { "2": "no" }],
      [["3", "4", "5"], "k=12. Yes — try smaller.", { "3": "yes" }],
      [["3"], "Least true k is 12.", { "3": "ans" }],
    ],
    { cells: ["k=4", "k=6", "k=8", "k=12", "k=16", "k=24"].map((value, i) => ({ id: String(i), value })) },
  ),
  "dsa:two-pointers": diagram(
    "pointers",
    "L and R fingers",
    [],
    [],
    "Need sum 11. Too big → R left. Too small → L right.",
    [
      [["0", "4"], "1+11=12 too big → move R.", { "0": "L", "4": "R" }],
      [["0", "3"], "1+7=8 too small → move L.", { "0": "L", "3": "R" }],
      [["1", "3"], "2+7=9 too small → move L.", { "1": "L", "3": "R" }],
      [["2", "3"], "4+7=11. Pair found.", { "2": "L", "3": "R" }],
    ],
    { cells: [1, 2, 4, 7, 11].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:sliding-window-fixed": diagram(
    "window",
    "Box of width k",
    [],
    [],
    "k=3. Slide one: drop the left, add the new right. Never rebuild the sum.",
    [
      [["0", "1", "2"], "Window [2,1,5] = 8.", { "0": "L", "2": "R" }],
      [["1", "2", "3"], "Drop 2, add 1 → 7.", { "1": "L", "3": "R" }],
      [["2", "3", "4"], "Drop 1, add 3 → 9. Best.", { "2": "L", "4": "R" }],
    ],
    { cells: [2, 1, 5, 1, 3].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:sliding-window-variable": diagram(
    "window",
    "Grow and shrink",
    [],
    [],
    "Longest window with sum ≤ 7. Expand R; while invalid, move L.",
    [
      [["0", "1"], "Grow: [2,1] = 3. OK.", { "0": "L", "1": "R" }],
      [["0", "1", "2"], "Grow: +5 = 8. Too big.", { "0": "L", "2": "R" }],
      [["1", "2"], "Shrink L. [1,5] = 6. OK.", { "1": "L", "2": "R" }],
      [["1", "2", "3"], "Grow: +1 = 7. Best length 3.", { "1": "L", "3": "R" }],
    ],
    { cells: [2, 1, 5, 1, 3].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:fast-slow-pointers": diagram(
    "list",
    "Turtle and hare",
    [
      ["a", "3", "cell"],
      ["b", "1", "cell"],
      ["c", "4", "cell"],
      ["d", "1", "cell"],
      ["e", "5", "cell"],
    ],
    [
      ["a", "b", "next"],
      ["b", "c", "next"],
      ["c", "d", "next"],
      ["d", "e", "next"],
      ["e", "c", "cycle", "dashed"],
    ],
    "Slow +1, fast +2. They meet inside the cycle. Reset one to head to find the start.",
    [
      [["a", "a"], "Both at head."],
      [["b", "c"], "Slow at 1, fast at 4."],
      [["c", "e"], "Slow at 4, fast at 5."],
      [["d", "d"], "Meet at 1. Cycle exists."],
    ],
  ),
  "dsa:bfs": diagram(
    "graph",
    "Layer by layer",
    [
      ["A", "A 0", "actor", 50, 12],
      ["B", "B 1", "cell", 28, 42],
      ["C", "C 1", "cell", 72, 42],
      ["D", "D 2", "cell", 14, 74],
      ["E", "E 2", "cell", 50, 74],
      ["F", "F 2", "cell", 86, 74],
    ],
    [
      ["A", "B"],
      ["A", "C"],
      ["B", "D"],
      ["B", "E"],
      ["C", "F"],
    ],
    "Queue holds the next layer. First visit is the hop-shortest path.",
    [
      [["A"], "Queue: A. Dist 0."],
      [["A", "B", "C"], "Pop A. Enqueue B, C — layer 1."],
      [["B", "D", "E"], "Pop B. Enqueue D, E — layer 2."],
      [["C", "F"], "Pop C. Enqueue F. First visit = shortest hops."],
    ],
  ),
  "dsa:dfs": diagram(
    "graph",
    "Dive, then backtrack",
    [
      ["A", "A", "actor", 50, 10],
      ["B", "B", "cell", 28, 32],
      ["D", "D", "cell", 18, 56],
      ["E", "E", "cell", 14, 82],
      ["C", "C", "cell", 78, 40],
    ],
    [
      ["A", "B"],
      ["B", "D"],
      ["D", "E"],
      ["A", "C"],
    ],
    "One deep path on the stack. Finish the branch, then the sibling.",
    [
      [["A"], "Start at A. Stack: A."],
      [["A", "B"], "Dive A → B. Sibling C waits."],
      [["A", "B", "D"], "Deeper: B → D."],
      [["A", "B", "D", "E"], "D → E. Dead end — pop back."],
      [["A", "C"], "Back at A. Now take C."],
    ],
  ),
  "dsa:dijkstra": diagram(
    "graph",
    "Cheapest so far",
    [
      ["S", "S 0", "actor", 12, 50],
      ["A", "A 3", "cell", 44, 20],
      ["B", "B 2", "cell", 44, 80],
      ["T", "T 4", "store", 86, 50],
    ],
    [
      ["S", "A", "4"],
      ["S", "B", "2"],
      ["B", "A", "1"],
      ["A", "T", "1"],
      ["B", "T", "5"],
    ],
    "Costs on nodes. Expand the cheapest known. First pop of T is final.",
    [
      [["S"], "dist S=0. Heap: S. Others ∞."],
      [["S", "B"], "Pop S. B=2 via edge 2. A=4 via edge 4."],
      [["S", "B", "A"], "Pop B. Relax A: 2+1=3. T via B: 2+5=7."],
      [["S", "B", "A", "T"], "Pop A. T via A: 3+1=4. Better. Done."],
    ],
  ),
  "dsa:union-find": diagram(
    "union-find",
    "Two groups, then one",
    [
      ["1", "1", "actor", 26, 18],
      ["2", "2", "cell", 12, 58],
      ["3", "3", "cell", 40, 58],
      ["4", "4", "actor", 74, 18],
      ["5", "5", "cell", 60, 58],
      ["6", "6", "cell", 88, 58],
    ],
    [
      ["2", "1"],
      ["3", "1"],
      ["5", "4"],
      ["6", "4"],
      ["1", "4", "union", "dashed"],
    ],
    "Two groups. Find walks to a root; union links the roots into one.",
    [
      [["2", "3", "5", "6"], "Six singletons. Each node is its own parent."],
      [["1", "2", "3"], "union(1,2), union(1,3). Left root = 1."],
      [["4", "5", "6"], "union(4,5), union(4,6). Right root = 4."],
      [["1", "4"], "union(1,4). Roots link. Now one set."],
    ],
  ),
  "dsa:knapsack-01": diagram(
    "dp-table",
    "Take or skip, once",
    [
      ["h0", "c0", "cell"],
      ["h1", "c1", "cell"],
      ["h2", "c2", "cell"],
      ["h3", "c3", "cell"],
      ["h4", "c4", "cell"],
      ["h5", "c5", "cell"],
      ["i0-0", "0", "cell"],
      ["i0-1", "0", "cell"],
      ["i0-2", "0", "cell"],
      ["i0-3", "0", "cell"],
      ["i0-4", "0", "cell"],
      ["i0-5", "0", "cell"],
      ["i1-0", "0", "cell"],
      ["i1-1", "0", "cell"],
      ["i1-2", "3", "cell"],
      ["i1-3", "3", "cell"],
      ["i1-4", "3", "cell"],
      ["i1-5", "3", "cell"],
      ["i2-0", "0", "cell"],
      ["i2-1", "0", "cell"],
      ["i2-2", "3", "cell"],
      ["i2-3", "4", "cell"],
      ["i2-4", "4", "cell"],
      ["i2-5", "7", "cell"],
    ],
    [],
    "Items (w=2,v=3) then (w=3,v=4). Capacity 5. Each item at most once — roll capacity backward.",
    [
      [["i0-0", "i0-1", "i0-2", "i0-3", "i0-4", "i0-5"], "Row 0: no items. All 0."],
      [["i1-2", "i1-3", "i1-4", "i1-5"], "Item 1 (2,3): fill c≥2 with 3."],
      [["i2-3", "i2-5"], "Item 2 (3,4): c=3 → 4; c=5 → 3+4=7. Answer 7."],
    ],
    {
      layout: "grid",
      lanes: [
        { id: "head", label: "cap", nodes: ["h0", "h1", "h2", "h3", "h4", "h5"] },
        { id: "r0", label: "∅", nodes: ["i0-0", "i0-1", "i0-2", "i0-3", "i0-4", "i0-5"] },
        { id: "r1", label: "+(2,3)", nodes: ["i1-0", "i1-1", "i1-2", "i1-3", "i1-4", "i1-5"] },
        { id: "r2", label: "+(3,4)", nodes: ["i2-0", "i2-1", "i2-2", "i2-3", "i2-4", "i2-5"] },
      ],
    },
  ),
  "dsa:coin-change": diagram(
    "array",
    "Fewest coins to make n",
    [],
    [],
    "1-D dp[x] = min coins to make x. Coins 1,3,4. Forward loop — unbounded.",
    [
      [["0"], "dp[0]=0.", { "0": "base" }],
      [["1", "3", "4"], "Coin 1 fills 1..n. Coin 3 then 4 overwrite better.", { "4": "coin" }],
      [["6"], "dp[6]=2 (3+3). Not 1+1+4 if worse.", { "6": "ans" }],
    ],
    { cells: ["0", "1", "2", "1", "1", "2", "2"].map((value, i) => ({ id: String(i), value })) },
  ),
  "dsa:lcs": diagram(
    "dp-table",
    "Two strings, one grid",
    [
      ["e", "LCS", "cell"],
      ["a", "A", "cell"],
      ["b", "B", "cell"],
      ["c", "C", "cell"],
      ["x", "A", "cell"],
      ["y", "C", "cell"],
      ["z", "B", "cell"],
      ["11", "1", "cell"],
      ["12", "1", "cell"],
      ["13", "1", "cell"],
      ["21", "1", "cell"],
      ["22", "1", "cell"],
      ["23", "2", "cell"],
      ["31", "1", "cell"],
      ["32", "2", "cell"],
      ["33", "2", "cell"],
    ],
    [],
    "ACE vs ABC. Match → diagonal +1. Else max(left, up). Answer 2 (A C).",
    [
      [["11"], "A=A. Diagonal 1."],
      [["23"], "C vs C after AB… = 2."],
      [["33"], "Bottom-right is LCS length."],
    ],
    {
      layout: "grid",
      lanes: [
        { id: "r1", label: "A", nodes: ["11", "12", "13"] },
        { id: "r2", label: "C", nodes: ["21", "22", "23"] },
        { id: "r3", label: "E", nodes: ["31", "32", "33"] },
      ],
    },
  ),
  "dsa:lis": diagram(
    "array",
    "Longest increasing tail",
    [],
    [],
    "Patience piles / tails array. 3,1,2,4 → LIS 1,2,4 length 3.",
    [
      [["0"], "3 starts pile 1.", { "0": "tail" }],
      [["1"], "1 replaces 3.", { "1": "tail" }],
      [["1", "2"], "2 extends.", { "2": "tail" }],
      [["1", "2", "3"], "4 extends. Length 3.", { "3": "ans" }],
    ],
    { cells: [3, 1, 2, 4].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:fibonacci-dp": diagram(
    "rec-tree",
    "Tree vs memo row",
    [
      ["f5", "f(5)", "actor"],
      ["f4", "f(4)", "cell"],
      ["f3a", "f(3)", "cell"],
      ["f3b", "f(3)", "cell"],
      ["f2", "f(2)", "cache"],
    ],
    [
      ["f5", "f4"],
      ["f5", "f3a"],
      ["f4", "f3b"],
      ["f4", "f2"],
    ],
    "Naive tree repeats f(3). Bottom-up row [1,1,2,3,5] computes each once.",
    [
      [["f5"], "Ask f(5)."],
      [["f5", "f4", "f3a"], "Two children. f(3) will be asked twice."],
      [["f2"], "Memo: store f(n) so the second call is O(1)."],
    ],
  ),
  "dsa:grid-dp": diagram(
    "dp-table",
    "Only right or down",
    [
      ["a", "1", "cell"],
      ["b", "1", "cell"],
      ["c", "1", "cell"],
      ["d", "1", "cell"],
      ["e", "2", "cell"],
      ["f", "3", "cell"],
      ["g", "1", "cell"],
      ["h", "3", "cell"],
      ["i", "6", "cell"],
    ],
    [],
    "Unique paths on a 3×3. Cell = from-left + from-above.",
    [
      [["a", "b", "c", "d", "g"], "First row and col are 1."],
      [["e"], "1+1=2."],
      [["i"], "3+3=6 paths to the corner."],
    ],
    {
      layout: "grid",
      lanes: [
        { id: "r0", label: "r0", nodes: ["a", "b", "c"] },
        { id: "r1", label: "r1", nodes: ["d", "e", "f"] },
        { id: "r2", label: "r2", nodes: ["g", "h", "i"] },
      ],
    },
  ),
  "dsa:two-sum": diagram(
    "buckets",
    "Need and seen",
    [
      ["n0", "2", "cell"],
      ["n1", "7", "cell"],
      ["n2", "11", "cell"],
      ["n3", "15", "cell"],
      ["m7", "need 7", "cache"],
      ["hit", "7 @ i=1", "store"],
    ],
    [
      ["n0", "m7", "9-2"],
      ["n1", "hit", "found"],
    ],
    "Walk once. Map value→index. If target-x is already in the map, return the pair.",
    [
      [["n0", "m7"], "See 2. Store need 7."],
      [["n1", "hit"], "See 7. Need is waiting. Pair (0,1)."],
    ],
  ),
  "dsa:kadane": diagram(
    "array",
    "Best ending here",
    [],
    [],
    "At each i: extend the streak or restart. Track global max.",
    [
      [["0"], "best = 2.", { "0": "cur" }],
      [["1"], "2 + (−3) = −1 < −3? Restart −3. Global still 2.", { "1": "cur" }],
      [["2"], "−3+4=1. Take 4. Global 4.", { "2": "cur" }],
      [["3"], "4+(−1)=3. Keep. Global 4.", { "3": "cur" }],
      [["4"], "3+5=8. Global 8.", { "4": "ans" }],
    ],
    { cells: [2, -3, 4, -1, 5].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:prefix-sum": diagram(
    "array",
    "Running totals",
    [],
    [],
    "pref[i] = a[0]+…+a[i]. Range [L,R] is pref[R]−pref[L−1].",
    [
      [["0"], "pref 2.", { "0": "p" }],
      [["1"], "2+1=3.", { "1": "p" }],
      [["3"], "Query [1,3] = 8−2 = 6.", { "1": "L", "3": "R" }],
    ],
    { cells: ["2", "3", "7", "8", "10"].map((value, i) => ({ id: String(i), value })) },
  ),
  "dsa:merge-sort": diagram(
    "bars",
    "Split, then zipper",
    [
      ["a", "4", "cell"],
      ["b", "1", "cell"],
      ["c", "3", "cell"],
      ["d", "2", "cell"],
    ],
    [],
    "Halves until one element, then merge two sorted runs.",
    [
      [["a", "b", "c", "d"], "Unsorted 4 1 3 2."],
      [["b", "a", "d", "c"], "Sorted pairs: 1,4 and 2,3."],
      [["b", "d", "c", "a"], "Zipper: 1,2,3,4."],
    ],
    { cells: [4, 1, 3, 2].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:quick-sort": diagram(
    "bars",
    "Pivot and partition",
    [
      ["a", "3", "cell"],
      ["b", "1", "cell"],
      ["c", "4", "cell"],
      ["d", "2", "cell"],
    ],
    [],
    "Pick a pivot. < pivot left, > pivot right. Recurse both sides.",
    [
      [["c"], "Pivot 4."],
      [["a", "b", "d", "c"], "Partition: 3,1,2 | 4."],
      [["b", "d", "a", "c"], "Recurse left → 1,2,3,4."],
    ],
    { cells: [3, 1, 4, 2].map((value, i) => ({ id: String(i), value: String(value) })) },
  ),
  "dsa:heapify": diagram(
    "heap",
    "Sift down to a heap",
    [
      ["r", "2", "actor", 50, 16],
      ["l", "8", "cell", 28, 48],
      ["ri", "5", "cell", 72, 48],
      ["ll", "3", "cell", 16, 80],
      ["lr", "4", "cell", 40, 80],
    ],
    [
      ["r", "l"],
      ["r", "ri"],
      ["l", "ll"],
      ["l", "lr"],
    ],
    "Parent must beat both children. Swap 2 with 8, then again if needed.",
    [
      [["r"], "2 is smaller than 8 and 5."],
      [["l", "r"], "Swap with larger child 8."],
      [["l"], "Heap property restored at the root."],
    ],
  ),
  "dsa:top-k": diagram(
    "heap",
    "A heap of size k",
    [
      ["h1", "5", "actor", 50, 18],
      ["h2", "7", "cell", 28, 52],
      ["h3", "9", "cell", 72, 52],
      ["x", "4", "queue", 50, 86],
    ],
    [
      ["h1", "h2"],
      ["h1", "h3"],
    ],
    "Min-heap of the best k. Next item 4 < root 5 — ignore. 10 would pop 5 and push 10.",
    [
      [["h1", "h2", "h3"], "Heap holds 5,7,9. k=3."],
      [["x"], "See 4. Smaller than min — discard."],
    ],
  ),
  "dsa:trie": diagram(
    "trie",
    "Prefix tree",
    [
      ["root", "·", "actor", 50, 10],
      ["c", "c", "cell", 30, 32],
      ["ca", "a", "cell", 30, 54],
      ["cat", "t*", "store", 16, 78],
      ["car", "r*", "store", 44, 78],
      ["b", "b", "cell", 74, 32],
      ["ba", "a", "cell", 74, 54],
      ["bat", "t*", "store", 74, 78],
    ],
    [
      ["root", "c"],
      ["c", "ca"],
      ["ca", "cat", "cat"],
      ["ca", "car", "car"],
      ["root", "b"],
      ["b", "ba"],
      ["ba", "bat", "bat"],
    ],
    "Shared prefixes share a path. A word ends on a marked leaf.",
    [
      [["root", "c", "ca", "cat"], "Insert cat. Path c-a-t. Mark t."],
      [["c", "ca", "car"], "Insert car. Branch after ca."],
      [["b", "ba", "bat"], "Insert bat. New first letter."],
      [["c", "ca"], "startsWith(ca)? Node a exists — yes."],
    ],
  ),
  "dsa:tree-traversals": diagram(
    "tree",
    "When you visit",
    [
      ["A", "A", "actor", 50, 12],
      ["B", "B", "cell", 26, 40],
      ["C", "C", "cell", 74, 40],
      ["D", "D", "cell", 12, 72],
      ["E", "E", "cell", 40, 72],
      ["F", "F", "cell", 74, 72],
    ],
    [
      ["A", "B"],
      ["A", "C"],
      ["B", "D"],
      ["B", "E"],
      ["C", "F"],
    ],
    "Same tree, three visit times: before kids, between, or after.",
    [
      [["A"], "Pre: visit A first, then kids."],
      [["A", "B", "D", "E", "C", "F"], "Pre: A B D E C F."],
      [["D", "B", "E", "A", "C", "F"], "In: D B E A C F (left, node, right)."],
      [["D", "E", "B", "F", "C", "A"], "Post: D E B F C A (kids, then node)."],
    ],
  ),
  "dsa:lca": diagram(
    "tree",
    "Deepest shared ancestor",
    [
      ["A", "A", "actor", 50, 10],
      ["B", "B", "cell", 30, 34],
      ["C", "C", "cell", 76, 34],
      ["D", "D", "cell", 30, 58],
      ["P", "P", "store", 16, 84],
      ["Q", "Q", "store", 44, 84],
    ],
    [
      ["A", "B"],
      ["A", "C"],
      ["B", "D"],
      ["D", "P"],
      ["D", "Q"],
    ],
    "Walk up from both targets. The deepest node that covers both is the LCA.",
    [
      [["P", "Q"], "Query: LCA of P and Q."],
      [["P"], "DFS left of D finds P."],
      [["Q"], "DFS right of D finds Q."],
      [["D"], "D sees both sides. LCA is D, not A."],
    ],
  ),
  "dsa:reverse-linked-list": diagram(
    "list",
    "Three pointers",
    [
      ["a", "1", "cell"],
      ["b", "2", "cell"],
      ["c", "3", "cell"],
      ["d", "4", "cell"],
    ],
    [
      ["a", "b"],
      ["b", "c"],
      ["c", "d"],
    ],
    "prev, cur, next. Flip cur.next = prev. Slide the triple.",
    [
      [["a"], "prev=null, cur=1."],
      [["a", "b"], "1 → null. cur=2."],
      [["b", "a"], "2 → 1 → null."],
      [["d", "c", "b", "a"], "4 → 3 → 2 → 1."],
    ],
  ),
  "dsa:valid-parentheses": diagram(
    "stack",
    "Push open, pop match",
    [
      ["s0", "(", "cell"],
      ["s1", "[", "cell"],
      ["s2", "{", "cell"],
    ],
    [],
    "Opens go on the stack. A close must match the top or the string is invalid.",
    [
      [["s0"], "See (. Push."],
      [["s0", "s1"], "See [. Push."],
      [["s0"], "See ]. Pop [. Match."],
    ],
  ),
  "dsa:next-greater-element": diagram(
    "stack",
    "Monotonic decreasing",
    [
      ["a", "2", "cell"],
      ["b", "1", "cell"],
      ["c", "5", "cell"],
      ["d", "3", "cell"],
    ],
    [],
    "Walk left→right. Pop anything smaller than a[i] — a[i] is their next greater.",
    [
      [["a"], "Stack: 2."],
      [["a", "b"], "1 < 2. Push 1."],
      [["c"], "5 pops 1 then 2. Next greater of both is 5."],
    ],
  ),
  "dsa:kmp": diagram(
    "array",
    "Prefix table, no restart",
    [],
    [],
    "Pattern aaba. lps[i] = longest prefix that is a suffix. Mismatch jumps to lps.",
    [
      [["0", "1"], "aa — lps 0,1.", { "1": "lps=1" }],
      [["2"], "aab — b breaks. lps=0.", { "2": "lps=0" }],
      [["3"], "aaba — last a matches prefix. lps=1.", { "3": "lps=1" }],
    ],
    { cells: ["a", "a", "b", "a"].map((value, i) => ({ id: String(i), value })) },
  ),
  "dsa:topo-sort-kahn": diagram(
    "graph",
    "Peel indegree 0",
    [
      ["A", "A 0", "actor", 14, 22],
      ["B", "B 1", "cell", 50, 22],
      ["C", "C 1", "cell", 14, 62],
      ["D", "D 2", "store", 82, 42],
    ],
    [
      ["A", "B"],
      ["A", "C"],
      ["B", "D"],
      ["C", "D"],
    ],
    "Start at indegree 0. Pop a node and its outgoing edges vanish.",
    [
      [["A"], "Only A has indegree 0. Queue: A."],
      [["A", "B", "C"], "Pop A. Edges A→B, A→C gone. B,C now 0."],
      [["B", "C", "D"], "Pop B then C. Both edges into D vanish."],
      [["D"], "D falls to 0. Order: A, B, C, D."],
    ],
  ),
  "dsa:islands": diagram(
    "dp-table",
    "Flood each land blob",
    [
      ["a", "1", "cell"],
      ["b", "1", "cell"],
      ["c", "0", "cell"],
      ["d", "0", "cell"],
      ["e", "1", "cell"],
      ["f", "1", "cell"],
      ["g", "0", "cell"],
      ["h", "0", "cell"],
      ["i", "1", "cell"],
      ["j", "1", "cell"],
      ["k", "0", "cell"],
      ["l", "0", "cell"],
      ["m", "0", "cell"],
      ["n", "1", "cell"],
      ["o", "0", "cell"],
      ["p", "0", "cell"],
      ["q", "1", "cell"],
      ["r", "0", "cell"],
      ["s", "0", "cell"],
      ["t", "0", "cell"],
    ],
    [],
    "Each unmarked 1 starts a flood. One flood = one island.",
    [
      [["a", "b", "f"], "Hit a 1. Flood island 1 (3 cells)."],
      [["e", "i", "j", "n"], "Next unmarked 1. Flood island 2."],
      [["q"], "Last land. Island 3. Count = 3."],
    ],
    {
      layout: "grid",
      lanes: [
        { id: "r0", label: "", nodes: ["a", "b", "c", "d", "e"] },
        { id: "r1", label: "", nodes: ["f", "g", "h", "i", "j"] },
        { id: "r2", label: "", nodes: ["k", "l", "m", "n", "o"] },
        { id: "r3", label: "", nodes: ["p", "q", "r", "s", "t"] },
      ],
    },
  ),
  "hld:url-shortener": diagram(
    "split",
    "Mint vs redirect",
    [
      ["cw", "Client", "client"],
      ["post", "POST", "service"],
      ["id", "ID→62", "worker"],
      ["dbw", "SQL", "store"],
      ["cr", "Client", "client"],
      ["get", "GET /x", "edge"],
      ["redis", "Redis", "cache"],
      ["dbr", "SQL", "store"],
      ["go", "302", "edge"],
    ],
    [
      ["cw", "post", "mint"],
      ["post", "id"],
      ["id", "dbw"],
      ["cr", "get", "read"],
      ["get", "redis"],
      ["redis", "dbr", "miss"],
      ["dbr", "go"],
    ],
    "Write mints a code. Read is Redis → SQL → 302. No analytics on this hop.",
    [
      [["cw", "post", "id", "dbw"], "Mint: Snowflake → base62, insert, return."],
      [["cr", "get", "redis"], "Hit: 302 now."],
      [["get", "dbr", "go"], "Miss: SQL, fill Redis, 302."],
    ],
    {
      lanes: [
        { id: "w", label: "POST mint", nodes: ["cw", "post", "id", "dbw"] },
        { id: "r", label: "GET redirect", nodes: ["cr", "get", "redis", "dbr", "go"] },
      ],
    },
  ),
  "hld:newsfeed": diagram(
    "compare",
    "Write fan-out vs read pull",
    [
      ["post", "Post", "client"],
      ["f1", "Inbox A", "cache"],
      ["f2", "Inbox B", "cache"],
      ["f3", "Inbox C", "cache"],
      ["celeb", "Celeb TL", "store"],
      ["me", "Merge", "service"],
    ],
    [
      ["post", "f1", "push"],
      ["post", "f2"],
      ["post", "f3"],
      ["celeb", "me", "pull"],
    ],
    "Normal: push ids into follower inboxes. Celebrity: pull at read, then merge.",
    [
      [["post", "f1", "f2", "f3"], "Fan-out on write."],
      [["celeb"], "Skip 50M inbox writes."],
      [["celeb", "me"], "Read: inbox + celeb TL + hydrate."],
    ],
    {
      lanes: [
        { id: "w", label: "Fan-out write", nodes: ["post", "f1", "f2", "f3"] },
        { id: "r", label: "Fan-out read", nodes: ["celeb", "me"] },
      ],
    },
  ),
  "hld:chat": diagram(
    "flow",
    "WS + presence, persist, push",
    [
      ["phone", "Phone", "client"],
      ["ws", "WS + presence", "edge"],
      ["log", "Persist", "store"],
      ["on", "Online socket", "service"],
      ["off", "Offline inbox", "queue"],
    ],
    [
      ["phone", "ws"],
      ["ws", "log", "ack after write"],
      ["log", "on"],
      ["log", "off", "if away"],
    ],
    "Socket holds presence. Persist first. Online gets the event; offline waits in an inbox.",
    [
      [["phone", "ws"], "WS up. Heartbeat = presence."],
      [["ws", "log"], "Write log, then ack sent."],
      [["on"], "Online: pubsub to the other socket."],
      [["off"], "Away: per-user inbox + push."],
    ],
  ),
  "hld:uber": diagram(
    "flow",
    "Ping cells, offer, lock",
    [
      ["drv", "Driver ping", "actor"],
      ["geo", "S2 cells", "cache"],
      ["match", "Matcher", "service"],
      ["offer", "Offer TTL", "policy"],
      ["lock", "CAS trip", "store"],
    ],
    [
      ["drv", "geo", "location"],
      ["geo", "match", "nearby"],
      ["match", "offer"],
      ["offer", "lock"],
    ],
    "Supply streams into cells. One offer at a time. CAS so two drivers cannot win.",
    [
      [["drv", "geo"], "Pings land in live cells."],
      [["match", "geo"], "Cover pickup, rank ETA."],
      [["offer"], "Offer one driver. Timeout → next."],
      [["lock"], "Accept: CAS busy, trip starts."],
    ],
  ),
  "hld:rate-limiting": diagram(
    "buckets",
    "Token bucket",
    [
      ["req", "Request", "client"],
      ["t3", "●●●", "cell"],
      ["t2", "●●", "cell"],
      ["t1", "●", "cell"],
      ["no", "429", "cut"],
    ],
    [
      ["req", "t3", "spend"],
      ["t3", "t2"],
      ["t2", "t1"],
      ["t1", "no", "empty"],
    ],
    "Refill at rate r, burst b. Spend a token or 429 + Retry-After.",
    [
      [["t3"], "Full: burst of 3."],
      [["req", "t2"], "Spend one. Two left."],
      [["t1"], "Last token."],
      [["no"], "Empty — 429."],
    ],
  ),
  "hld:notifications": diagram(
    "fanout",
    "One event, many channels",
    [
      ["ev", "Like event", "client"],
      ["pref", "Prefs / quiet", "policy"],
      ["in", "Inbox", "store"],
      ["push", "APNs / FCM", "queue"],
      ["mail", "Email digest", "worker"],
    ],
    [
      ["ev", "pref"],
      ["pref", "in"],
      ["pref", "push"],
      ["pref", "mail"],
    ],
    "Filter prefs, write inbox, then channel workers. Never send from the like request.",
    [
      [["ev"], "Product outbox → bus."],
      [["pref"], "Quiet hours / mute / dedup."],
      [["in", "push"], "Inbox + push now."],
      [["mail"], "Low priority: batch email."],
    ],
  ),
  "hld:autocomplete": diagram(
    "flow",
    "Prefix at keystroke QPS",
    [
      ["q", "\"an\"", "client"],
      ["cdn", "Redis / CDN", "cache"],
      ["trie", "Hot trie", "service"],
      ["tail", "Tail index", "store"],
      ["k", "Top K", "edge"],
    ],
    [
      ["q", "cdn"],
      ["cdn", "trie", "miss"],
      ["trie", "tail", "rare"],
      ["tail", "k"],
    ],
    "Hot prefixes are a replicated memory trie. Tail falls to a completion index. Re-rank after fetch.",
    [
      [["q", "cdn"], "Keystroke. Cache hit → done."],
      [["trie"], "Popular: in-memory prefix walk."],
      [["tail"], "Long tail: n-gram / ES."],
      [["k"], "Return K. Personalize only as rerank."],
    ],
  ),
  "hld:web-crawler": diagram(
    "flow",
    "Frontier, polite fetch",
    [
      ["front", "Frontier", "queue"],
      ["tok", "Host bucket", "policy"],
      ["get", "Fetch", "worker"],
      ["parse", "Parse links", "service"],
      ["seen", "Seen / bloom", "store"],
    ],
    [
      ["front", "tok"],
      ["tok", "get"],
      ["get", "parse"],
      ["parse", "seen"],
    ],
    "Shard the frontier by host. A per-host bucket is politeness. Dedup before enqueue.",
    [
      [["front", "tok"], "Host has a token? Else wait."],
      [["get"], "Fetch. Respect robots."],
      [["parse", "seen"], "Canonicalize. New? Enqueue."],
      [["seen"], "Old hash → skip store."],
    ],
  ),
  "hld:maps-nearby": diagram(
    "buckets",
    "Cover the circle",
    [
      ["pin", "lat,lng,r", "client"],
      ["c1", "Cell 12", "cell"],
      ["c2", "Cell 13", "cell"],
      ["c3", "Cell 21", "cell"],
      ["k", "Top K", "service"],
    ],
    [
      ["pin", "c1", "cover"],
      ["pin", "c2"],
      ["pin", "c3"],
      ["c1", "k", "haversine"],
    ],
    "Cells that cover the radius, then exact distance. Do not scan the world table.",
    [
      [["pin"], "Query: pin + radius."],
      [["c1", "c2", "c3"], "Covering S2 / geohash cells."],
      [["k"], "Exact km filter, rank, cap K."],
    ],
  ),
  "hld:youtube": diagram(
    "flow",
    "Upload → ladder → CDN",
    [
      ["up", "Master PUT", "client"],
      ["job", "Transcode", "worker"],
      ["hls", "HLS / DASH", "store"],
      ["cdn", "CDN PoP", "edge"],
      ["play", "ABR player", "client"],
    ],
    [
      ["up", "job"],
      ["job", "hls", "ladder"],
      ["hls", "cdn"],
      ["cdn", "play"],
    ],
    "One master. Many bitrates. Player fetches segments from the edge, not the API.",
    [
      [["up"], "Multipart master to object store."],
      [["job", "hls"], "Probe, ladder, package."],
      [["cdn", "play"], "Manifest + segments via CDN."],
      [["cdn"], "Viral: shield origin, more PoPs."],
    ],
  ),
  "hld:dropbox": diagram(
    "split",
    "Blocks vs metadata",
    [
      ["file", "File", "client"],
      ["hash", "Chunk hash", "worker"],
      ["s3", "Block store", "store"],
      ["tree", "Tree / rev", "store"],
      ["cas", "CAS commit", "policy"],
      ["note", "Device notify", "queue"],
    ],
    [
      ["file", "hash"],
      ["hash", "s3", "missing only"],
      ["tree", "cas"],
      ["cas", "note"],
    ],
    "Bytes are content-addressed chunks. The tree is a CAS revision. Sync is the journal, not S3 listings.",
    [
      [["file", "hash", "s3"], "Hash chunks. Upload misses only."],
      [["tree", "cas"], "Commit if parent rev still matches."],
      [["note"], "Other devices pull the new rev."],
      [["cas"], "Same parent twice → conflict copy."],
    ],
    {
      lanes: [
        { id: "b", label: "Blocks", nodes: ["file", "hash", "s3"] },
        { id: "m", label: "Metadata", nodes: ["tree", "cas", "note"] },
      ],
    },
  ),
  "hld:unique-id-generator": diagram(
    "split",
    "Snowflake vs tickets",
    [
      ["ts", "41-bit ms", "cell"],
      ["wk", "10-bit worker", "policy"],
      ["seq", "12-bit seq", "cell"],
      ["sql", "Ticket table", "store"],
      ["rng", "[lo, hi)", "cache"],
      ["mint", "Next id", "service"],
    ],
    [
      ["ts", "wk"],
      ["wk", "seq"],
      ["sql", "rng"],
      ["rng", "mint"],
    ],
    "Snowflake: time + worker + seq, no hot path RPC. Tickets: cache a range from SQL.",
    [
      [["ts", "wk", "seq"], "64 bits. Clock + lease + seq."],
      [["wk"], "Worker id from lease. Fence pauses."],
      [["sql", "rng", "mint"], "Leaf: bump high-water, mint local."],
    ],
    {
      lanes: [
        { id: "s", label: "Snowflake", nodes: ["ts", "wk", "seq"] },
        { id: "t", label: "Ticket range", nodes: ["sql", "rng", "mint"] },
      ],
    },
  ),
  "hld:cap-theorem": diagram(
    "cut",
    "Partition, then pick",
    [
      ["a", "Replica A", "store"],
      ["b", "Replica B", "store"],
      ["cp", "CP refuse", "policy"],
      ["ap", "AP accept", "policy"],
    ],
    [
      ["a", "b", "partition", "cut"],
      ["a", "cp"],
      ["b", "ap"],
    ],
    "Cable gone. Fail closed (CP) or take the write and repair (AP).",
    [
      [["a", "b"], "Healthy: both talk."],
      [["a", "b"], "P is forced. The link is gone."],
      [["cp"], "Money, alias, seat — error."],
      [["ap"], "Likes, ticks — accept, merge later."],
    ],
  ),
  "hld:consistent-hashing": diagram(
    "ring",
    "Walk the ring",
    [
      ["s1", "S1", "store", 50, 12],
      ["s2", "S2", "store", 88, 50],
      ["s3", "S3", "store", 50, 88],
      ["s4", "S4", "store", 12, 50],
      ["k1", "kA", "cell", 70, 22],
      ["k2", "kB", "cell", 78, 70],
    ],
    [
      ["k1", "s2", "clock"],
      ["k2", "s3", "clock"],
    ],
    "Hash nodes and keys onto a circle. Clockwise owner. Add a node — only the nearby arc moves.",
    [
      [["s1", "s2", "s3", "s4"], "Nodes (and vnodes) on the ring."],
      [["k1", "s2"], "kA walks clockwise → S2."],
      [["k2", "s3"], "kB → S3."],
      [["s2"], "S2 dies. Its arc goes to the next node, not everyone."],
    ],
  ),
  "hld:load-balancers": diagram(
    "compare",
    "L4 packets vs L7 requests",
    [
      ["c4", "TCP flow", "client"],
      ["l4", "L4 VIP", "edge"],
      ["a4", "App", "service"],
      ["c7", "HTTP", "client"],
      ["l7", "L7 VIP", "edge"],
      ["a7", "/video fleet", "service"],
    ],
    [
      ["c4", "l4", "5-tuple"],
      ["l4", "a4"],
      ["c7", "l7", "path"],
      ["l7", "a7"],
    ],
    "L4 sprays connections. L7 reads host/path, canaries, health on a real URL.",
    [
      [["c4", "l4", "a4"], "L4: 5-tuple → backend. TLS can pass through."],
      [["c7", "l7", "a7"], "L7: route /video, drain, least-request."],
    ],
    {
      lanes: [
        { id: "l4", label: "L4", nodes: ["c4", "l4", "a4"] },
        { id: "l7", label: "L7", nodes: ["c7", "l7", "a7"] },
      ],
    },
  ),
  "hld:cache-patterns": diagram(
    "flow",
    "Aside, then one miss",
    [
      ["app", "App", "service"],
      ["c", "Cache", "cache"],
      ["db", "DB", "store"],
      ["lock", "Single-flight", "policy"],
    ],
    [
      ["app", "c", "get"],
      ["c", "db", "miss"],
      ["db", "c", "fill"],
      ["lock", "db", "one flyer"],
    ],
    "Cache-aside: app get/fill. Delete on write. One lock so expiry is not a stampede.",
    [
      [["app", "c"], "Hit — return."],
      [["app", "db", "c"], "Miss — DB, fill, TTL."],
      [["lock"], "Herd: one walk to DB."],
    ],
  ),
  "hld:sharding": diagram(
    "buckets",
    "Key → shard",
    [
      ["k", "user_id", "client"],
      ["h", "hash % N", "service"],
      ["s0", "Shard 0", "store"],
      ["s1", "Shard 1", "store"],
      ["s2", "Shard 2", "store"],
    ],
    [
      ["k", "h"],
      ["h", "s1", "slot 1"],
    ],
    "Range, hash, or directory. A hot key stays hot — it does not split itself.",
    [
      [["k", "h"], "Pick the shard key."],
      [["s0", "s1", "s2"], "Each shard is its own primary."],
      [["s1"], "This user always hits shard 1."],
      [["s2"], "Celebrity / time-range: split or isolate the whale."],
    ],
  ),
  "hld:kafka-sqs-rabbit": diagram(
    "compare",
    "Log vs hide vs bind",
    [
      ["kp", "Produce", "client"],
      ["part", "P0 P1 P2", "queue"],
      ["off", "Offset", "store"],
      ["sq", "SQS", "queue"],
      ["vis", "Visibility", "policy"],
      ["dlq", "DLQ", "queue"],
      ["ex", "Exchange", "service"],
      ["rq", "Bound q", "queue"],
    ],
    [
      ["kp", "part", "key"],
      ["part", "off"],
      ["sq", "vis"],
      ["vis", "dlq"],
      ["ex", "rq", "bind"],
    ],
    "Kafka: partition log + offset, replay. SQS: hide, then DLQ. Rabbit: exchange → queue.",
    [
      [["kp", "part", "off"], "Kafka: one owner per partition. Rewind offset."],
      [["sq", "vis", "dlq"], "SQS: visibility timeout; crash → reappear."],
      [["ex", "rq"], "Rabbit: route, then compete on the queue."],
    ],
    {
      lanes: [
        { id: "k", label: "Kafka", nodes: ["kp", "part", "off"] },
        { id: "s", label: "SQS", nodes: ["sq", "vis", "dlq"] },
        { id: "r", label: "Rabbit", nodes: ["ex", "rq"] },
      ],
    },
  ),
  "hld:queues-pubsub-streams": diagram(
    "compare",
    "Three async shapes",
    [
      ["q", "Queue", "queue"],
      ["qw", "One worker", "worker"],
      ["pub", "Pub/sub", "service"],
      ["s1", "Sub A", "worker"],
      ["s2", "Sub B", "worker"],
      ["st", "Stream", "store"],
      ["r", "Replay", "client"],
    ],
    [
      ["q", "qw", "compete"],
      ["pub", "s1", "fan-out"],
      ["pub", "s2"],
      ["st", "r", "offset"],
    ],
    "Queue: one worker wins. Pub/sub: every sub fires. Stream: log + offset, rewind.",
    [
      [["q", "qw"], "Queue — compete."],
      [["pub", "s1", "s2"], "Pub/sub — both fire."],
      [["st", "r"], "Stream — read offset 42 again."],
    ],
    {
      lanes: [
        { id: "a", label: "Queue", nodes: ["q", "qw"] },
        { id: "b", label: "Pub/sub", nodes: ["pub", "s1", "s2"] },
        { id: "c", label: "Stream", nodes: ["st", "r"] },
      ],
    },
  ),
  "hld:replication": diagram(
    "split",
    "Primary, then replicas",
    [
      ["w", "Write", "client"],
      ["p", "Primary", "store"],
      ["r1", "Replica", "store"],
      ["r2", "Replica", "store"],
      ["rd", "Read", "client"],
    ],
    [
      ["w", "p"],
      ["p", "r1", "sync or async"],
      ["p", "r2"],
      ["rd", "r1"],
    ],
    "Writes land on a primary. Replicas follow. Sync = safer, slower. Async = faster, stale reads.",
    [
      [["w", "p"], "Write on primary."],
      [["p", "r1", "r2"], "Ship the log."],
      [["rd", "r1"], "Reads may be stale if async."],
    ],
    {
      lanes: [
        { id: "wr", label: "Write", nodes: ["w", "p"] },
        { id: "rep", label: "Replicate", nodes: ["r1", "r2"] },
        { id: "rd", label: "Read", nodes: ["rd"] },
      ],
    },
  ),
  "hld:sql-vs-nosql": diagram(
    "compare",
    "Access pattern picks the store",
    [
      ["sql", "SQL", "store"],
      ["rel", "Joins, txns", "service"],
      ["no", "NoSQL / KV", "store"],
      ["kv", "Key + scan", "cache"],
    ],
    [
      ["sql", "rel"],
      ["no", "kv"],
    ],
    "SQL when you need relations and transactions. KV when the key is the query.",
    [
      [["sql", "rel"], "Checkout, ledger, unique alias — SQL."],
      [["no", "kv"], "Session, cache, wide fan-out — KV."],
    ],
    {
      lanes: [
        { id: "s", label: "SQL", nodes: ["sql", "rel"] },
        { id: "n", label: "NoSQL", nodes: ["no", "kv"] },
      ],
    },
  ),
  "hld:monolith-vs-microservices": diagram(
    "compare",
    "One deploy vs many",
    [
      ["mono", "Modular monolith", "service"],
      ["db", "One DB", "store"],
      ["m1", "Orders", "service"],
      ["m2", "Billing", "service"],
      ["q", "Events", "queue"],
    ],
    [
      ["mono", "db"],
      ["m1", "q"],
      ["q", "m2"],
    ],
    "Start modular in one process. Split when a team or scale axis forces a network boundary.",
    [
      [["mono", "db"], "One deploy, in-process calls."],
      [["m1", "q", "m2"], "Split: async events, separate fail."],
    ],
  ),
  "lld:parking-lot": diagram(
    "tree",
    "Lot owns floors owns spots",
    [
      ["lot", "ParkingLot", "class", 50, 12],
      ["f1", "Floor 1", "class", 28, 40],
      ["f2", "Floor 2", "class", 72, 40],
      ["s1", "Spot A", "cell", 16, 68],
      ["s2", "Spot B", "cell", 40, 68],
      ["s3", "Spot C", "cell", 72, 68],
      ["t", "Ticket", "store", 28, 92],
      ["fee", "FeePolicy", "iface", 72, 92],
    ],
    [
      ["lot", "f1"],
      ["lot", "f2"],
      ["f1", "s1"],
      ["f1", "s2"],
      ["f2", "s3"],
      ["s1", "t", "occupy"],
      ["t", "fee", "quote"],
    ],
    "Aggregate is the lot. occupy() is the invariant. Fees are a strategy, not a switch in unpark.",
    [
      [["lot", "f1", "f2"], "Lot → floors → spots."],
      [["s1", "t"], "find + occupy atomically → ticket."],
      [["fee"], "Weekend rate = new FeePolicy. park() stays."],
    ],
  ),
  "lld:elevator": diagram(
    "shaft",
    "Car, floors, request queue",
    [
      ["f5", "5", "cell"],
      ["f4", "4", "cell"],
      ["f3", "3 car", "actor"],
      ["f2", "2", "cell"],
      ["f1", "1", "cell"],
      ["q", "5↑  8  2↓", "queue"],
      ["idle", "Idle", "state"],
      ["move", "Moving", "state"],
      ["open", "Door", "state"],
    ],
    [
      ["idle", "move"],
      ["move", "open"],
      ["open", "idle"],
    ],
    "Each car is a state machine. A scheduler (strategy) assigns hall calls. SCAN is not hardcoded in the car.",
    [
      [["f3", "q"], "Car at 3. Queue: 5↑, 8, 2↓."],
      [["move", "f5"], "Moving up toward 5."],
      [["open"], "Arrive, door, clear stop, recompute direction."],
    ],
  ),
  "lld:strategy-pattern": diagram(
    "classes",
    "Swap the algorithm",
    [
      ["ctx", "Checkout", "class"],
      ["pol", "Payment", "iface"],
      ["a", "Card", "policy"],
      ["b", "UPI", "policy"],
    ],
    [
      ["ctx", "pol", "charge()"],
      ["a", "pol", "implements"],
      ["b", "pol", "implements"],
    ],
    "Context holds an interface. Card and UPI are two classes. No switch in checkout.",
    [
      [["ctx", "pol"], "Checkout calls payment.charge."],
      [["a"], "Card is one brain."],
      [["b"], "UPI is another. Add Wallet the same way."],
    ],
  ),
  "lld:observer-pattern": diagram(
    "fanout",
    "Subject notifies listeners",
    [
      ["sub", "Subject / ticker", "class"],
      ["ch", "Chart", "actor"],
      ["al", "Alert", "actor"],
      ["log", "Log", "actor"],
    ],
    [
      ["sub", "ch", "notify"],
      ["sub", "al", "notify"],
      ["sub", "log", "notify"],
    ],
    "State changes once. Chart, Alert, Log each react. Subscribe/unsubscribe without editing Subject.",
    [
      [["sub"], "Price updates."],
      [["ch", "al", "log"], "Each observer gets the event."],
    ],
  ),
  "lld:singleton-pattern": diagram(
    "decision",
    "One instance — usually a smell",
    [
      ["new", "new Logger()", "cut"],
      ["get", "Logger.get()", "policy"],
      ["one", "Shared instance", "store"],
    ],
    [
      ["new", "one", "many copies"],
      ["get", "one", "one copy"],
    ],
    "Hide the constructor. Everyone gets the same object. Hard to test — prefer DI unless it is a real process singleton.",
    [
      [["new"], "Three news → three loggers. Lost lines."],
      [["get", "one"], "get() always returns the same."],
    ],
  ),
  "lld:factory-method": diagram(
    "classes",
    "Creator defers the class",
    [
      ["c", "Factory", "iface"],
      ["a", "CarFactory", "class"],
      ["b", "BikeFactory", "class"],
      ["p", "Vehicle", "iface"],
    ],
    [
      ["a", "c"],
      ["b", "c"],
      ["a", "p", "create()"],
    ],
    "Caller asks a factory for a Vehicle. New vehicle type = new factory, not a growing switch.",
    [
      [["c", "p"], "Interface in, product out."],
      [["a", "b"], "Two creators. Add TruckFactory later."],
    ],
  ),
  "lld:decorator-pattern": diagram(
    "layers",
    "Wrap, do not subclass",
    [
      ["core", "Stream", "iface"],
      ["buf", "Buffered", "class"],
      ["zip", "Gzip", "class"],
      ["app", "Caller", "actor"],
    ],
    [
      ["app", "zip"],
      ["zip", "buf"],
      ["buf", "core"],
    ],
    "Same interface at every layer. Add behavior by wrapping, not by a subclass explosion.",
    [
      [["app", "zip"], "Caller talks to GzipStream."],
      [["zip", "buf", "core"], "Each wrapper forwards."],
    ],
  ),
  "lld:state-pattern": diagram(
    "states",
    "The object changes kind",
    [
      ["idle", "Idle", "state"],
      ["move", "Moving", "state"],
      ["open", "Open", "state"],
      ["ctx", "Car", "class"],
    ],
    [
      ["idle", "move", "hall call"],
      ["move", "open", "arrive"],
      ["open", "idle", "close"],
      ["ctx", "idle", "holds"],
    ],
    "State objects implement the same events. The car delegates. Adding Maintenance is a new class.",
    [
      [["idle"], "Idle ignores car-calls except to start."],
      [["move"], "Moving queues stops."],
      [["open"], "Open starts a door timer."],
    ],
  ),
  "lld:splitwise": diagram(
    "classes",
    "Ledger, then balances",
    [
      ["exp", "Expense", "class"],
      ["sp", "Split", "class"],
      ["led", "Ledger", "service"],
      ["bal", "Balances", "store"],
      ["sim", "Simplify", "policy"],
    ],
    [
      ["exp", "sp", "sums to total"],
      ["led", "exp", "append"],
      ["led", "bal", "project"],
      ["sim", "bal", "optional"],
    ],
    "Store expenses. Balances are a projection. Simplify is a graph algorithm, not a cell mutate.",
    [
      [["exp", "sp"], "Splits must sum to the total."],
      [["led", "bal"], "apply() then recompute."],
      [["sim"], "Min-cash-flow is a later policy."],
    ],
  ),
  "lld:producer-consumer": diagram(
    "flow",
    "Bounded buffer",
    [
      ["p", "Producer", "actor"],
      ["q", "Blocking queue", "queue"],
      ["c", "Consumer", "worker"],
    ],
    [
      ["p", "q", "put"],
      ["q", "c", "take"],
    ],
    "Queue capacity is the backpressure. Full → producer waits. Empty → consumer waits.",
    [
      [["p", "q"], "put blocks if full."],
      [["q", "c"], "take blocks if empty."],
    ],
  ),
  "lld:hexagonal-architecture": diagram(
    "layers",
    "Domain in the middle",
    [
      ["ui", "HTTP / UI", "edge"],
      ["app", "Use case", "service"],
      ["dom", "Domain", "class"],
      ["db", "SQL adapter", "store"],
      ["pay", "Pay adapter", "policy"],
    ],
    [
      ["ui", "app"],
      ["app", "dom"],
      ["app", "db"],
      ["app", "pay"],
    ],
    "Domain does not import SQL. Adapters implement ports. Tests fake the ports.",
    [
      [["dom"], "Invariants live here."],
      [["app", "db", "pay"], "Ports point out."],
    ],
  ),
  "lld:solid-ocp": diagram(
    "classes",
    "Closed to edits, open to types",
    [
      ["svc", "ParkService", "class"],
      ["fee", "FeePolicy", "iface"],
      ["h", "Hourly", "policy"],
      ["w", "Weekend", "policy"],
    ],
    [
      ["svc", "fee"],
      ["h", "fee"],
      ["w", "fee"],
    ],
    "Adding weekend rates must not rewrite unpark(). New class, same interface.",
    [
      [["svc", "fee"], "Service already talks to a policy."],
      [["w"], "New variant = new class."],
    ],
  ),
};
