/** Canonical NeetCode practice lists (LeetCode slugs). */

export type NcMeta = {
  slug: string;
  title: string;
  difficulty: "easy" | "medium" | "hard";
  pattern: string;
  lc: number;
};

/** Blind / NeetCode 75 — start here. */
export const NEETCODE_75: NcMeta[] = [
  { slug: "contains-duplicate", title: "Contains Duplicate", difficulty: "easy", pattern: "Arrays & Hashing", lc: 217 },
  { slug: "valid-anagram", title: "Valid Anagram", difficulty: "easy", pattern: "Arrays & Hashing", lc: 242 },
  { slug: "two-sum", title: "Two Sum", difficulty: "easy", pattern: "Arrays & Hashing", lc: 1 },
  { slug: "group-anagrams", title: "Group Anagrams", difficulty: "medium", pattern: "Arrays & Hashing", lc: 49 },
  { slug: "top-k-frequent-elements", title: "Top K Frequent Elements", difficulty: "medium", pattern: "Arrays & Hashing", lc: 347 },
  { slug: "product-of-array-except-self", title: "Product of Array Except Self", difficulty: "medium", pattern: "Arrays & Hashing", lc: 238 },
  { slug: "encode-and-decode-strings", title: "Encode and Decode Strings", difficulty: "medium", pattern: "Arrays & Hashing", lc: 271 },
  { slug: "longest-consecutive-sequence", title: "Longest Consecutive Sequence", difficulty: "medium", pattern: "Arrays & Hashing", lc: 128 },
  { slug: "valid-palindrome", title: "Valid Palindrome", difficulty: "easy", pattern: "Two Pointers", lc: 125 },
  { slug: "3sum", title: "3Sum", difficulty: "medium", pattern: "Two Pointers", lc: 15 },
  { slug: "container-with-most-water", title: "Container With Most Water", difficulty: "medium", pattern: "Two Pointers", lc: 11 },
  { slug: "best-time-to-buy-and-sell-stock", title: "Best Time to Buy and Sell Stock", difficulty: "easy", pattern: "Sliding Window", lc: 121 },
  { slug: "longest-substring-without-repeating-characters", title: "Longest Substring Without Repeating Characters", difficulty: "medium", pattern: "Sliding Window", lc: 3 },
  { slug: "longest-repeating-character-replacement", title: "Longest Repeating Character Replacement", difficulty: "medium", pattern: "Sliding Window", lc: 424 },
  { slug: "minimum-window-substring", title: "Minimum Window Substring", difficulty: "hard", pattern: "Sliding Window", lc: 76 },
  { slug: "valid-parentheses", title: "Valid Parentheses", difficulty: "easy", pattern: "Stack", lc: 20 },
  { slug: "find-minimum-in-rotated-sorted-array", title: "Find Minimum in Rotated Sorted Array", difficulty: "medium", pattern: "Binary Search", lc: 153 },
  { slug: "search-in-rotated-sorted-array", title: "Search in Rotated Sorted Array", difficulty: "medium", pattern: "Binary Search", lc: 33 },
  { slug: "reverse-linked-list", title: "Reverse Linked List", difficulty: "easy", pattern: "Linked List", lc: 206 },
  { slug: "merge-two-sorted-lists", title: "Merge Two Sorted Lists", difficulty: "easy", pattern: "Linked List", lc: 21 },
  { slug: "reorder-list", title: "Reorder List", difficulty: "medium", pattern: "Linked List", lc: 143 },
  { slug: "remove-nth-node-from-end-of-list", title: "Remove Nth Node From End of List", difficulty: "medium", pattern: "Linked List", lc: 19 },
  { slug: "linked-list-cycle", title: "Linked List Cycle", difficulty: "easy", pattern: "Linked List", lc: 141 },
  { slug: "merge-k-sorted-lists", title: "Merge k Sorted Lists", difficulty: "hard", pattern: "Linked List", lc: 23 },
  { slug: "maximum-depth-of-binary-tree", title: "Maximum Depth of Binary Tree", difficulty: "easy", pattern: "Trees", lc: 104 },
  { slug: "same-tree", title: "Same Tree", difficulty: "easy", pattern: "Trees", lc: 100 },
  { slug: "invert-binary-tree", title: "Invert Binary Tree", difficulty: "easy", pattern: "Trees", lc: 226 },
  { slug: "binary-tree-maximum-path-sum", title: "Binary Tree Maximum Path Sum", difficulty: "hard", pattern: "Trees", lc: 124 },
  { slug: "binary-tree-level-order-traversal", title: "Binary Tree Level Order Traversal", difficulty: "medium", pattern: "Trees", lc: 102 },
  { slug: "serialize-and-deserialize-binary-tree", title: "Serialize and Deserialize Binary Tree", difficulty: "hard", pattern: "Trees", lc: 297 },
  { slug: "subtree-of-another-tree", title: "Subtree of Another Tree", difficulty: "easy", pattern: "Trees", lc: 572 },
  { slug: "construct-binary-tree-from-preorder-and-inorder-traversal", title: "Construct Binary Tree from Preorder and Inorder Traversal", difficulty: "medium", pattern: "Trees", lc: 105 },
  { slug: "validate-binary-search-tree", title: "Validate Binary Search Tree", difficulty: "medium", pattern: "Trees", lc: 98 },
  { slug: "kth-smallest-element-in-a-bst", title: "Kth Smallest Element in a BST", difficulty: "medium", pattern: "Trees", lc: 230 },
  { slug: "lowest-common-ancestor-of-a-binary-search-tree", title: "Lowest Common Ancestor of a BST", difficulty: "medium", pattern: "Trees", lc: 235 },
  { slug: "implement-trie-prefix-tree", title: "Implement Trie (Prefix Tree)", difficulty: "medium", pattern: "Tries", lc: 208 },
  { slug: "design-add-and-search-words-data-structure", title: "Design Add and Search Words", difficulty: "medium", pattern: "Tries", lc: 211 },
  { slug: "word-search-ii", title: "Word Search II", difficulty: "hard", pattern: "Tries", lc: 212 },
  { slug: "number-of-islands", title: "Number of Islands", difficulty: "medium", pattern: "Graphs", lc: 200 },
  { slug: "clone-graph", title: "Clone Graph", difficulty: "medium", pattern: "Graphs", lc: 133 },
  { slug: "pacific-atlantic-water-flow", title: "Pacific Atlantic Water Flow", difficulty: "medium", pattern: "Graphs", lc: 417 },
  { slug: "course-schedule", title: "Course Schedule", difficulty: "medium", pattern: "Graphs", lc: 207 },
  { slug: "graph-valid-tree", title: "Graph Valid Tree", difficulty: "medium", pattern: "Graphs", lc: 261 },
  { slug: "number-of-connected-components-in-an-undirected-graph", title: "Number of Connected Components", difficulty: "medium", pattern: "Graphs", lc: 323 },
  { slug: "alien-dictionary", title: "Alien Dictionary", difficulty: "hard", pattern: "Graphs", lc: 269 },
  { slug: "climbing-stairs", title: "Climbing Stairs", difficulty: "easy", pattern: "1-D DP", lc: 70 },
  { slug: "house-robber", title: "House Robber", difficulty: "medium", pattern: "1-D DP", lc: 198 },
  { slug: "house-robber-ii", title: "House Robber II", difficulty: "medium", pattern: "1-D DP", lc: 213 },
  { slug: "longest-palindromic-substring", title: "Longest Palindromic Substring", difficulty: "medium", pattern: "1-D DP", lc: 5 },
  { slug: "palindromic-substrings", title: "Palindromic Substrings", difficulty: "medium", pattern: "1-D DP", lc: 647 },
  { slug: "decode-ways", title: "Decode Ways", difficulty: "medium", pattern: "1-D DP", lc: 91 },
  { slug: "coin-change", title: "Coin Change", difficulty: "medium", pattern: "1-D DP", lc: 322 },
  { slug: "maximum-product-subarray", title: "Maximum Product Subarray", difficulty: "medium", pattern: "1-D DP", lc: 152 },
  { slug: "word-break", title: "Word Break", difficulty: "medium", pattern: "1-D DP", lc: 139 },
  { slug: "longest-increasing-subsequence", title: "Longest Increasing Subsequence", difficulty: "medium", pattern: "1-D DP", lc: 300 },
  { slug: "combination-sum", title: "Combination Sum", difficulty: "medium", pattern: "Backtracking", lc: 39 },
  { slug: "word-search", title: "Word Search", difficulty: "medium", pattern: "Backtracking", lc: 79 },
  { slug: "unique-paths", title: "Unique Paths", difficulty: "medium", pattern: "2-D DP", lc: 62 },
  { slug: "longest-common-subsequence", title: "Longest Common Subsequence", difficulty: "medium", pattern: "2-D DP", lc: 1143 },
  { slug: "jump-game", title: "Jump Game", difficulty: "medium", pattern: "Greedy", lc: 55 },
  { slug: "maximum-subarray", title: "Maximum Subarray", difficulty: "medium", pattern: "Greedy", lc: 53 },
  { slug: "insert-interval", title: "Insert Interval", difficulty: "medium", pattern: "Intervals", lc: 57 },
  { slug: "merge-intervals", title: "Merge Intervals", difficulty: "medium", pattern: "Intervals", lc: 56 },
  { slug: "non-overlapping-intervals", title: "Non-overlapping Intervals", difficulty: "medium", pattern: "Intervals", lc: 435 },
  { slug: "meeting-rooms", title: "Meeting Rooms", difficulty: "easy", pattern: "Intervals", lc: 252 },
  { slug: "meeting-rooms-ii", title: "Meeting Rooms II", difficulty: "medium", pattern: "Intervals", lc: 253 },
  { slug: "rotate-image", title: "Rotate Image", difficulty: "medium", pattern: "Math & Geometry", lc: 48 },
  { slug: "spiral-matrix", title: "Spiral Matrix", difficulty: "medium", pattern: "Math & Geometry", lc: 54 },
  { slug: "set-matrix-zeroes", title: "Set Matrix Zeroes", difficulty: "medium", pattern: "Math & Geometry", lc: 73 },
  { slug: "number-of-1-bits", title: "Number of 1 Bits", difficulty: "easy", pattern: "Bit Manipulation", lc: 191 },
  { slug: "counting-bits", title: "Counting Bits", difficulty: "easy", pattern: "Bit Manipulation", lc: 338 },
  { slug: "reverse-bits", title: "Reverse Bits", difficulty: "easy", pattern: "Bit Manipulation", lc: 190 },
  { slug: "missing-number", title: "Missing Number", difficulty: "easy", pattern: "Bit Manipulation", lc: 268 },
  { slug: "sum-of-two-integers", title: "Sum of Two Integers", difficulty: "medium", pattern: "Bit Manipulation", lc: 371 },
  { slug: "find-median-from-data-stream", title: "Find Median from Data Stream", difficulty: "hard", pattern: "Heap", lc: 295 },
];

/** Full NeetCode 150 (includes the 75). */
export const NEETCODE_150_SLUGS: string[] = [
  "contains-duplicate",
  "valid-anagram",
  "two-sum",
  "group-anagrams",
  "top-k-frequent-elements",
  "product-of-array-except-self",
  "valid-sudoku",
  "encode-and-decode-strings",
  "longest-consecutive-sequence",
  "valid-palindrome",
  "two-sum-ii-input-array-is-sorted",
  "3sum",
  "container-with-most-water",
  "trapping-rain-water",
  "best-time-to-buy-and-sell-stock",
  "longest-substring-without-repeating-characters",
  "longest-repeating-character-replacement",
  "permutation-in-string",
  "minimum-window-substring",
  "sliding-window-maximum",
  "valid-parentheses",
  "min-stack",
  "evaluate-reverse-polish-notation",
  "generate-parentheses",
  "daily-temperatures",
  "car-fleet",
  "largest-rectangle-in-histogram",
  "binary-search",
  "search-a-2d-matrix",
  "koko-eating-bananas",
  "find-minimum-in-rotated-sorted-array",
  "search-in-rotated-sorted-array",
  "time-based-key-value-store",
  "median-of-two-sorted-arrays",
  "reverse-linked-list",
  "merge-two-sorted-lists",
  "reorder-list",
  "remove-nth-node-from-end-of-list",
  "copy-list-with-random-pointer",
  "add-two-numbers",
  "linked-list-cycle",
  "find-the-duplicate-number",
  "lru-cache",
  "merge-k-sorted-lists",
  "reverse-nodes-in-k-group",
  "invert-binary-tree",
  "maximum-depth-of-binary-tree",
  "diameter-of-binary-tree",
  "balanced-binary-tree",
  "same-tree",
  "subtree-of-another-tree",
  "lowest-common-ancestor-of-a-binary-search-tree",
  "binary-tree-level-order-traversal",
  "binary-tree-right-side-view",
  "count-good-nodes-in-binary-tree",
  "validate-binary-search-tree",
  "kth-smallest-element-in-a-bst",
  "construct-binary-tree-from-preorder-and-inorder-traversal",
  "binary-tree-maximum-path-sum",
  "serialize-and-deserialize-binary-tree",
  "implement-trie-prefix-tree",
  "design-add-and-search-words-data-structure",
  "word-search-ii",
  "find-median-from-data-stream",
  "k-closest-points-to-origin",
  "last-stone-weight",
  "kth-largest-element-in-a-stream",
  "kth-largest-element-in-an-array",
  "task-scheduler",
  "design-twitter",
  "subsets",
  "combination-sum",
  "permutations",
  "subsets-ii",
  "combination-sum-ii",
  "word-search",
  "palindrome-partitioning",
  "letter-combinations-of-a-phone-number",
  "n-queens",
  "number-of-islands",
  "max-area-of-island",
  "clone-graph",
  "walls-and-gates",
  "rotting-oranges",
  "pacific-atlantic-water-flow",
  "surrounded-regions",
  "course-schedule",
  "course-schedule-ii",
  "graph-valid-tree",
  "number-of-connected-components-in-an-undirected-graph",
  "redundant-connection",
  "word-ladder",
  "reconstruct-itinerary",
  "min-cost-to-connect-all-points",
  "network-delay-time",
  "swim-in-rising-water",
  "alien-dictionary",
  "cheapest-flights-within-k-stops",
  "climbing-stairs",
  "min-cost-climbing-stairs",
  "house-robber",
  "house-robber-ii",
  "longest-palindromic-substring",
  "palindromic-substrings",
  "decode-ways",
  "coin-change",
  "maximum-product-subarray",
  "word-break",
  "longest-increasing-subsequence",
  "partition-equal-subset-sum",
  "unique-paths",
  "longest-common-subsequence",
  "best-time-to-buy-and-sell-stock-with-cooldown",
  "coin-change-ii",
  "target-sum",
  "interleaving-string",
  "longest-increasing-path-in-a-matrix",
  "distinct-subsequences",
  "edit-distance",
  "burst-balloons",
  "partition-to-k-equal-sum-subsets",
  "maximum-subarray",
  "jump-game",
  "jump-game-ii",
  "gas-station",
  "hand-of-straights",
  "merge-triplets-to-form-target-triplet",
  "partition-labels",
  "valid-parenthesis-string",
  "insert-interval",
  "merge-intervals",
  "non-overlapping-intervals",
  "meeting-rooms",
  "meeting-rooms-ii",
  "minimum-interval-to-include-each-query",
  "rotate-image",
  "spiral-matrix",
  "set-matrix-zeroes",
  "happy-number",
  "plus-one",
  "powx-n",
  "multiply-strings",
  "detect-squares",
  "single-number",
  "number-of-1-bits",
  "counting-bits",
  "reverse-bits",
  "missing-number",
  "sum-of-two-integers",
  "reverse-integer",
];

const NC75_SET = new Set(NEETCODE_75.map((p) => p.slug));

/** Problems in NeetCode 150 that are not in the 75 — learn these after. */
export function neetcode150Extras(): string[] {
  return NEETCODE_150_SLUGS.filter((slug) => !NC75_SET.has(slug));
}

export function ncTopicSlug(leetcodeSlug: string) {
  return `nc-${leetcodeSlug}`;
}
