import type { Topic } from "../schema";

function ai(
  slug: string,
  category: string,
  title: string,
  fields: Omit<Topic, "slug" | "track" | "category" | "title" | "depth"> & { depth?: Topic["depth"] },
): Topic {
  return { slug, track: "ai", category, title, depth: fields.depth ?? "core", ...fields };
}

export const aiTopics: Topic[] = [
  ai("tokens", "Tokens & prompts", "The model counts pieces, not words", {
    summary: "A token is a chunk of text the model bills and reads. Words can be one token or several. You budget tokens, not pages.",
    whyItMatters: "Every applied-AI bug that starts “the model ignored the end of my file” is usually the window filling up. You cannot debug that if you still think in words.",
    theory: [
      "Tokenizers split text into a fixed vocabulary. “unbelievable” may be several pieces. Code and languages tokenize at different rates.",
      "APIs charge input tokens and output tokens separately. A fat system prompt is paid on every call.",
    ],
    howItWorks: [
      "Rough JS stand-in: split on spaces and punctuation, then treat each piece as one token.",
      "Real models use a trained tokenizer. You estimate, then measure with the provider’s count.",
      "When the count is over the window, the API rejects or silently drops the tail — ask which.",
    ],
    whenToUse: ["Any prompt, any RAG dump, any “paste the PDF” idea."],
    whenNotToUse: ["Do not use word count as the budget."],
    interviewTips: ["Say: I would count tokens, not characters, then decide what to drop."],
    pitfalls: ["Pasting a transcript and assuming the model saw the last message."],
    practiceIdeas: ["Estimate tokens for a 2k-word article. Then compare to a real tokenizer later."],
    related: ["context-window", "cost-latency"],
  }),
  ai("context-window", "Tokens & prompts", "The window fills up", {
    summary: "The context window is the max tokens of prompt + answer the model can hold at once. Overflow is a product bug, not a vibe.",
    whyItMatters: "RAG, chat history, and “put the schema in the prompt” all fight for the same box.",
    theory: [
      "Window = system + history + retrieved chunks + user + reserved output.",
      "Longer windows cost more and are slower. A 128k model is not a free dump truck.",
    ],
    howItWorks: [
      "Budget: reserve output first, then system, then the newest user turn, then retrieved pages, then old chat.",
      "Drop oldest history or lowest-score chunks when the sum is too big.",
      "Never assume the model read the last page of a pasted book.",
    ],
    whenToUse: ["Chat with memory, RAG, tool traces."],
    whenNotToUse: ["Tiny classification prompts — the window is not the issue."],
    interviewTips: ["Draw the budget boxes. Point at what you evict first."],
    pitfalls: ["Keeping the whole thread forever."],
    practiceIdeas: ["A 8k window, 1k system, 2k history, 6k retrieval — what do you cut?"],
    related: ["tokens", "retrieve-then-read", "cost-latency"],
  }),
  ai("prompt-as-spec", "Tokens & prompts", "The prompt is the spec", {
    summary: "A prompt is a contract: role, inputs, output shape, and what to do when unsure. It is not a pep talk.",
    whyItMatters: "Interviews and production both fail when the prompt is a paragraph of wishes. Specs you can test.",
    theory: [
      "Good spec: who you are, what sources you may use, the JSON or bullets you must return, the refuse rule.",
      "Bad spec: “be helpful and thorough” with no schema and no “I don’t know.”",
    ],
    howItWorks: [
      "Write the output schema first. Then the refuse line. Then the sources. Then tone.",
      "One change at a time. You cannot A/B a prompt you rewrote entirely.",
      "Put examples only if they show the schema, not extra trivia.",
    ],
    whenToUse: ["Every call you will eval later."],
    whenNotToUse: ["Playground doodling — still write a schema when you keep the prompt."],
    interviewTips: ["I would write the contract, then three failing inputs, then the prompt."],
    pitfalls: ["Hidden rules in a 800-word system blob nobody diffs."],
    practiceIdeas: ["Spec: answer only from the notes; else say UNKNOWN. Two examples."],
    related: ["temperature", "golden-eval", "hallucination"],
  }),
  ai("temperature", "Tokens & prompts", "Same question, different answers", {
    summary: "Temperature (and similar knobs) control how boldly the model samples. High = more variety. Low = more repeatable.",
    whyItMatters: "They will not say “set temperature.” They will say the SQL keeps changing or the summary is boring.",
    theory: [
      "Next-token pick is a weighted random over the vocabulary. Temperature flattens or sharpens those weights.",
      "Evals need a low temperature or you are scoring noise.",
    ],
    howItWorks: [
      "Classification, extraction, SQL: temperature near 0.",
      "Brainstorming titles: higher. Then you pick, the model does not ship raw.",
      "If two runs disagree on a fact task, the prompt or the retrieval is wrong — do not “average” them in prod.",
    ],
    whenToUse: ["You need either stability or variety — say which."],
    whenNotToUse: ["Do not use high temperature to hide a bad spec."],
    interviewTips: ["Fact path: I lock sampling. Creative path: I sample, then a checker."],
    pitfalls: ["Golden evals at temperature 1."],
    practiceIdeas: ["Same extract prompt at 0 and 1. Diff the JSON."],
    related: ["prompt-as-spec", "golden-eval", "text-to-sql"],
  }),
  ai("embeddings", "Meaning as numbers", "Meaning as a list of numbers", {
    summary: "An embedding is a list of numbers that stands for a piece of text so similar meanings sit nearby.",
    whyItMatters: "Search, RAG, and clustering all start here. You do not train this in week 3 — you call an API and store vectors.",
    theory: [
      "Same model, same text → same vector (usually). Different models’ numbers are not comparable.",
      "You store vectors next to the chunk id. At query time you embed the question and compare.",
    ],
    howItWorks: [
      "embed(text) → number[]. Save with the chunk.",
      "embed(question) → compare to stored vectors.",
      "In JS you can fake 2-D vectors to learn the idea before you pay for an API.",
    ],
    whenToUse: ["Semantic search, RAG, duplicate questions."],
    whenNotToUse: ["Exact IDs, emails, error codes — use equality or keyword."],
    interviewTips: ["I embed chunks offline. Online I embed the query and take top-k."],
    pitfalls: ["Mixing two embedding models in one index."],
    practiceIdeas: ["Draw reset-password and forgot-login close; draw pizza far away."],
    related: ["cosine-similarity", "keyword-vs-vector", "retrieve-then-read"],
  }),
  ai("cosine-similarity", "Meaning as numbers", "Which two lists point the same way", {
    summary: "Cosine similarity asks whether two vectors point the same direction, ignoring how long they are.",
    whyItMatters: "This is the usual score for “is this chunk about the question?” Length should not win just because the paragraph is long.",
    theory: [
      "cosine = dot(a,b) / (|a||b|). 1 = same direction, 0 = orthogonal, -1 = opposite.",
      "You rank chunks by this score, then take the top k that still fit the window.",
    ],
    howItWorks: [
      "In JS: dot product, then divide by the two lengths.",
      "Sort descending. Tie-break by recency if you have it.",
      "A high score is not “true.” It is “nearby in meaning-space.”",
    ],
    whenToUse: ["Ranking retrieved chunks."],
    whenNotToUse: ["Need an exact string match."],
    interviewTips: ["I rank by cosine, then I still apply a keyword or metadata filter if the domain needs it."],
    pitfalls: ["Treating 0.3 as a yes because it was the best of a bad set."],
    practiceIdeas: ["[1,0] vs [0.9,0.1] vs [0,1]. Who wins against query [1,0]?"],
    related: ["embeddings", "retrieve-then-read"],
  }),
  ai("keyword-vs-vector", "Meaning as numbers", "Ctrl+F is not enough", {
    summary: "Keyword search needs the same words. Vector search needs similar meaning. Real systems often use both.",
    whyItMatters: "Unity-style analytics language (“ARPDAU”, “D7 retain”) will miss if you only embed casual English — or only grep.",
    theory: [
      "Keyword / BM25 wins on IDs, codes, exact metric names.",
      "Vectors win on paraphrase. Hybrid: retrieve both, merge, rerank.",
    ],
    howItWorks: [
      "If the query has a token that looks like an ID or a metric name, keep keyword.",
      "Always run vector for the prose part.",
      "Intersect or fuse scores. Do not blindly take vector-only in a warehouse glossary.",
    ],
    whenToUse: ["Docs + jargon. Support + ticket IDs."],
    whenNotToUse: ["A three-row lookup table — SQL is enough."],
    interviewTips: ["Hybrid retrieval. I say when keyword must win."],
    pitfalls: ["Vector-only on a metrics dictionary."],
    practiceIdeas: ["Query “D7 retain” vs “players who came back after a week.”"],
    related: ["embeddings", "retrieve-then-read", "text-to-sql"],
  }),
  ai("chunking", "RAG", "Cut the book into pages the model can hold", {
    summary: "Chunking splits a source into pieces you can embed and fit in the window. Too big = noisy. Too small = no context.",
    whyItMatters: "Bad chunks make RAG look “dumb” when the model never saw a complete thought.",
    theory: [
      "Split on headings and paragraphs first, not every 200 characters mid-sentence.",
      "Overlap a little so a sentence on a boundary is not lost.",
    ],
    howItWorks: [
      "Prefer structure (markdown headings) over a blind character cut.",
      "Keep a pointer: source id, heading, updated-at.",
      "Re-chunk when the doc changes. Old vectors lie.",
    ],
    whenToUse: ["Any corpus bigger than the window."],
    whenNotToUse: ["A 20-line policy — one chunk is fine."],
    interviewTips: ["I chunk on structure, store metadata, and I can show a bad split."],
    pitfalls: ["Slicing a table so the header is in another chunk."],
    practiceIdeas: ["Split this README on ## headings. Print the first 40 tokens of each."],
    related: ["retrieve-then-read", "stale-context", "context-window"],
  }),
  ai("retrieve-then-read", "RAG", "Find pages, then answer", {
    summary: "RAG: retrieve a few chunks, then ask the model to answer only from those pages. Retrieval is the product. The model is the reader.",
    whyItMatters: "This is the default applied-AI design. Interviews start here, not at fine-tuning.",
    theory: [
      "Index offline. Query → embed → top-k → stuff into the prompt with the spec → answer + citations.",
      "If retrieval is wrong, a smarter model still answers the wrong pages.",
    ],
    howItWorks: [
      "Show the chunks in the prompt as numbered sources.",
      "Require citations like [2] or UNKNOWN.",
      "Log which chunk ids were used. That is how you debug.",
    ],
    whenToUse: ["Questions over your docs, tickets, metrics glossary."],
    whenNotToUse: ["The answer must be computed (sum this table) — retrieve, then a tool or SQL."],
    interviewTips: ["v1 is retrieve-then-read with citations. Fine-tune is v3."],
    pitfalls: ["Dumping 40 chunks and hoping."],
    practiceIdeas: ["Three chunks, one question, force UNKNOWN if none apply."],
    related: ["chunking", "hallucination", "golden-eval"],
  }),
  ai("stale-context", "RAG", "The docs changed yesterday", {
    summary: "The index can be newer or older than the source of truth. Stale chunks make confident wrong answers.",
    whyItMatters: "Production RAG dies on “we updated the FAQ.” Interviews love this follow-up.",
    theory: [
      "Every chunk needs updated-at and a source version. Re-embed on change.",
      "Deletes must remove vectors. Orphans keep answering.",
    ],
    howItWorks: [
      "On publish: delete old ids, write new chunks, embed.",
      "If you cannot reindex live, put a “as of date” in the answer spec.",
      "A human-owned source (warehouse metric) beats a blog post in the index.",
    ],
    whenToUse: ["Any corpus that moves."],
    whenNotToUse: ["A frozen textbook dump — still version it once."],
    interviewTips: ["I treat the index like a cache. Invalidation is part of v1."],
    pitfalls: ["Embedding once at launch and never again."],
    practiceIdeas: ["Change one sentence. Show the old chunk still winning until you reindex."],
    related: ["chunking", "retrieve-then-read"],
  }),
  ai("function-calling", "Tools & evals", "Let the model call your function", {
    summary: "Tool calling: the model returns a function name and JSON args. Your JS runs it. The model does not invent the result.",
    whyItMatters: "This is how you get live data, SQL, and side effects without stuffing the world into the prompt.",
    theory: [
      "You declare tools with a JSON schema. The model picks or refuses.",
      "You execute, then send the result back for the final English.",
    ],
    howItWorks: [
      "Keep tools tiny: getMetric({name, start, end}), not doAnything({sql}).",
      "Validate args in JS before running.",
      "The model can still pick the wrong tool — eval that.",
    ],
    whenToUse: ["Live numbers, tickets, calendar, SQL runner."],
    whenNotToUse: ["A static FAQ — RAG is enough."],
    interviewTips: ["The model proposes. My code is the source of truth."],
    pitfalls: ["A tool that accepts raw SQL with no check."],
    practiceIdeas: ["One tool add(a,b). Model must call it for “what is 2+3”."],
    related: ["text-to-sql", "hallucination", "prompt-as-spec"],
  }),
  ai("hallucination", "Tools & evals", "It sounds sure and is wrong", {
    summary: "A hallucination is a fluent claim that is not in the sources or the tools. The voice does not tell you.",
    whyItMatters: "This is the fear stakeholders have. Your job is a refuse path and an eval, not “we used GPT-x.”",
    theory: [
      "Grounding: answer only from retrieved text or tool output.",
      "If neither has it, say UNKNOWN. That is a feature.",
    ],
    howItWorks: [
      "Citations required. No citation → fail the eval.",
      "Ask a question you know is missing. The correct answer is UNKNOWN.",
      "Do not reward longer answers.",
    ],
    whenToUse: ["Any user-facing answer."],
    whenNotToUse: ["Fiction and brainstorming — label them as such."],
    interviewTips: ["I have a missing-info test in the golden set."],
    pitfalls: ["“Be helpful” without a refuse."],
    practiceIdeas: ["Notes about parking. Ask about refunds. Expect UNKNOWN."],
    related: ["retrieve-then-read", "golden-eval", "prompt-as-spec"],
  }),
  ai("golden-eval", "Tools & evals", "A tiny test set you trust", {
    summary: "A golden eval is a short list of questions with the answers you will accept. You run it on every prompt change.",
    whyItMatters: "Applied AI jobs (Unity included) care that you can score a change. Vibes are not a ship gate.",
    theory: [
      "Start with 10–30 items: easy, paraphrase, missing-info, nasty jargon.",
      "Score: exact facts, citation present, UNKNOWN when needed. Not “sounds nice.”",
    ],
    howItWorks: [
      "Store {id, question, mustInclude[], mustNot[], expectUnknown}.",
      "Run the pipeline. Pass/fail. Diff vs last run.",
      "A prompt change that fails an old pass does not ship.",
    ],
    whenToUse: ["Before you demo. Before you tweak the prompt again."],
    whenNotToUse: ["One-off playground."],
    interviewTips: ["I would show the eval table, not a chat screenshot."],
    pitfalls: ["Thirty vague “good/bad” ratings with no expected fact."],
    practiceIdeas: ["10 questions on your notes RAG. Two must be UNKNOWN."],
    related: ["hallucination", "prompt-as-spec", "text-to-sql"],
  }),
  ai("text-to-sql", "Data & SQL", "English in, SQL out — then check it", {
    summary: "The model writes a query. Your job is the warehouse schema, the allow-list, and a dry-run. The model does not run wild.",
    whyItMatters: "Analytics + applied AI interviews live here. SQL you already know. The new part is the check.",
    theory: [
      "Give the model only the tables it may touch. Certified metrics beat “dump information_schema.”",
      "Reject non-SELECT. Require a partition or date filter on big tables.",
    ],
    howItWorks: [
      "Retrieve the metric definition first (RAG on the glossary).",
      "Generate SQL. Parse it. Run EXPLAIN or a LIMIT dry-run.",
      "If the user asked for a delete, refuse in the spec — never a tool.",
    ],
    whenToUse: ["Analysts asking English over a warehouse."],
    whenNotToUse: ["A single known dashboard number — just query it."],
    interviewTips: ["Retrieve the metric, generate, validate, then run. Human in the loop for spend."],
    pitfalls: ["Passing raw generated SQL to the warehouse."],
    practiceIdeas: ["Schema: plays(day, game, revenue). “Top game yesterday.” Check the WHERE."],
    related: ["keyword-vs-vector", "function-calling", "golden-eval", "analytics-qa-design"],
  }),
  ai("cost-latency", "Ship", "Tokens cost money and time", {
    summary: "Each call has input tokens, output tokens, and milliseconds. Cache what does not change. Shrink what does.",
    whyItMatters: "A correct answer that costs $2 and 8 seconds will not ship. Interviews ask where you cut.",
    theory: [
      "Input is often the bill (RAG dumps). Output length is the wait.",
      "Cache system prompts and repeated retrievals. Smaller model for classify, bigger for the last write.",
    ],
    howItWorks: [
      "Log tokens in, tokens out, ms, cache hit.",
      "Cap output tokens. Summarize history instead of sending the thread.",
      "Batch embeddings offline.",
    ],
    whenToUse: ["Anything past a demo."],
    whenNotToUse: ["Your first ten evals — make them right first, then cheap."],
    interviewTips: ["I would show the budget and one cache."],
    pitfalls: ["Re-embedding the corpus on every question."],
    practiceIdeas: ["Same answer with 6k vs 800 of context. Compare tokens and quality eval."],
    related: ["tokens", "context-window", "retrieve-then-read"],
  }),
  ai("pii-in-prompts", "Ship", "Do not paste the customer", {
    summary: "Prompts and logs are copies of the data. Emails, phones, and health text do not belong there raw.",
    whyItMatters: "You already felt this in healthcare-shaped interviews. Applied AI fails compliance before it fails BLEU.",
    theory: [
      "Redact before the model. Minimize what you log. The vendor is another copy.",
      "Need the fact, not the identifier: “adult user in US” not the SSN.",
    ],
    howItWorks: [
      "Regex + allow-list fields before embed and before complete.",
      "Do not put raw transcripts in traces you keep forever.",
      "If the task needs the identifier, that is a different, reviewed path.",
    ],
    whenToUse: ["Support, billing, any user content."],
    whenNotToUse: ["Public docs with no people."],
    interviewTips: ["Redact first. I can say what I strip."],
    pitfalls: ["Pasting a ticket into ChatGPT to “just summarize.”"],
    practiceIdeas: ["Redact emails and phones in a sample ticket before embed."],
    related: ["golden-eval", "analytics-qa-design"],
  }),
  ai("analytics-qa-design", "Interview", "Design Q&A over analytics", {
    summary: "Whiteboard: analysts ask English, the warehouse is BigQuery, answers must be correct enough to spend against. v1 is glossary + SQL + eval, not a chatbot skin.",
    whyItMatters: "This is the Unity-shaped design. Same 7-step HLD habit: lock v1, then the dangerous hop.",
    theory: [
      "Read path: question → retrieve certified metric → SQL → validate → run → cite the metric id.",
      "Write path is not the chat. Metrics are owned in git or a metrics layer.",
    ],
    howItWorks: [
      "v1: ten golden questions, one domain (revenue). No open internet.",
      "Human approve if estimated bytes scanned is huge.",
      "Follow-up: join path, cache, and what you do when two metrics disagree.",
    ],
    whenToUse: ["Applied AI + analytics interviews."],
    whenNotToUse: ["A consumer chat toy with no warehouse."],
    interviewTips: ["Start from the question and the lie you refuse to tell. Then boxes."],
    pitfalls: ["Drawing six agents before the glossary."],
    practiceIdeas: ["Two-minute v1. Then they add “compare to last season.”"],
    related: ["text-to-sql", "golden-eval", "retrieve-then-read", "cost-latency"],
  }),
];
